### ISSUE TITLE
Preserve referential equality if possible

### ISSUE THREAD

**Issue by gaearon** [kolodny/immutability-helper#1]
We’re planning to deprecate `react-addons-update` so if you’d like to continue the development we’ll be happy to point people to your repo instead.

If you’re up for it, I wondered if you’d like to port over the changes made in https://github.com/facebook/react/pull/6353? We planned to merge this but it probably won’t make it into 15 so I think it would be best to just do the same thing in this project now. Feel free to copy the tests and then tweak the implementation to match https://github.com/facebook/react/pull/6353 as you see fit.

Cheers!

**Comment by kolodny** [comment]
Sure, I'd be happy to help. I plan on continuing to maintain this project. I'll work on incorporating facebook/react#6353  into this project. I'll ping you when I'm done with those changes

Thanks!

**Comment by kolodny** [comment]
done at 6171d78

**Comment by gaearon** [comment]
Thanks!
