### ISSUE TITLE
How to update an array element given index stored in a variable

### ISSUE THREAD

**Issue by hongyuan1306** [kolodny/immutability-helper#10]
While the following code in the doc works fine:

```
var collection = [1, 2, {a: [12, 17, 15]}];
var newCollection = update(collection, {2: {a: {$splice: [[1, 1, 13, 14]]}}});
```

If I use a variable to store the element index, as in the code:

```
var idx = 2;
var collection = [1, 2, {a: [12, 17, 15]}];
var newCollection = update(collection, {idx: {a: {$splice: [[1, 1, 13, 14]]}}});
```

the following exception will be raised:

```
TypeError: Cannot read property 'a' of undefined
    at update (/home/hong/Sencha/web/website/node_modules/immutability-helper/index.js:50:42)
    at update (/home/hong/Sencha/web/website/node_modules/immutability-helper/index.js:50:29)
```

Quite often in a list the index of the element to be updated is not known beforehand but found out via the `findIndex` method and saved in a variable.

How shall the code be written in this case?

**Comment by kolodny** [comment]
You need to use square brackets around the `idx` variable in the key so it's a [computed property](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer#Computed_property_names)

```js
var idx = 2;
var collection = [1, 2, {a: [12, 17, 15]}];
console.log(  { idx : {a: {$splice: [[1, 1, 13, 14]]}}}  ) // {"idx":{"a":{"$splice":[[1,1,13,14]]}}}
console.log(  {[idx]: {a: {$splice: [[1, 1, 13, 14]]}}}  ) // {"2":{"a":{"$splice":[[1,1,13,14]]}}}
```

**Comment by hongyuan1306** [comment]
Works like charm. Thanks.
