### ISSUE TITLE
can i use this helper in Redux? how i can do that?  plaese tall me，thk

### ISSUE THREAD

**Issue by chenyinlong** [kolodny/immutability-helper#101]
can i use this helper in Redux? how i can do that?  plaese tall me，thk

i want do some thing help in RN,but i do not want use immutable.js ,and i find "helper",
can i use this in Redux?

**Comment by kolodny** [comment]
Hi @chenyinlong 

The basic react usage would be something like

```js
this.setState(update(this.state, {
  deeply: {
    nested: {
      property: {$set: 123}
    }
  }
}));
```

In [redux](https://redux.js.org/basics/reducers) it would be something like

```js
function todoApp(state = initialState, action) {
  switch (action.type) {
    case SET_VISIBILITY_FILTER:
      return update(state, {
        visibilityFilter: {$set: action.filter}
      });
    default:
      return state
  }
}
```
