### ISSUE TITLE
 Confused about part of code

### ISSUE THREAD

**Issue by DYS1230** [kolodny/immutability-helper#105]
I read the code to study, but I confused about part of code.
```
    getAllKeys(spec).forEach(function(key) {
      if (hasOwnProperty.call(commands, key)) {
        var objectWasNextObject = object === nextObject;
        nextObject = commands[key](spec[key], nextObject, spec, object);
        if (objectWasNextObject && update.isEquals(nextObject, object)) {
          nextObject = object;
        }
      } else {
        ...
      }
    })
```
why need `nextObject = object;`
when `isEquals` is `true`, which condition `nextObject` will not euqal `object` ? thk.

**Comment by kolodny** [comment]
Take a look at https://github.com/kolodny/immutability-helper/commit/18b6b5de7b458a6c39a88960b637b53e2f67bc04 where we attempt to maintain the same object if we detect that nothing changed on the object in a more robust fashion. For example

```js
const state = {a: 1};
const updated = update(state, {a: {$set: 1}});
state === updated; // true
```

That's essentially what this  bit of code is doing. It also is giving a bit more power in that if `isEqual` does a deep check, it will still bump the `nextObject` back to the correct value
