### ISSUE TITLE
isEquals fails for shallow direct apply

### ISSUE THREAD

**Issue by RebelusQuo** [kolodny/immutability-helper#106]
When `update` is called with a shallow direct apply function the immutable checks are bypassed, because there is no outer `update` invocation that checks object equality.

I am writing my own take on this library based of this code base which means I have not run this code with the testing libraries of your choice, and thus I submit this as an issue rather than a pull request. This should be the relevant test, and change to the implementation:

```
  it('supports an escape hatch for isEqual for shallow direct apply', function() {
    myUpdate.isEquals = function(a, b) {
      return JSON.stringify(a) === JSON.stringify(b);
    };
    var a = { b: 1 };
    var b = myUpdate(a, function() { return { b: 1 }; });
    expect(a).toBe(b);
  });
```

```
  function update(object, spec) {
    if (typeof spec === 'function') {
      spec = { $apply: spec };
    }
    ...
```

**Comment by kolodny** [comment]
Awesome, Thanks for the issue and the fix. I'm published the updated library with the fix to `v2.7.1`
