### ISSUE TITLE
Support object with prototypes

### ISSUE THREAD

**Issue by RebelusQuo** [kolodny/immutability-helper#107]
The library currently supports object without prototypes (`Object.create(null)`) and derived objects, but not objects with a simple prototype. This use case should be supported in my opinion. Code for test and changed implementation here (like last time, not verified):

```
  it('supports objects with prototypes', function() {
    var proto = { a: 'Proto' };
    var obj = Object.create(proto);
    expect(update(obj, { $merge: { b: 'Obj' } }).a).toEqual('Proto');
  });
```

```
  ...
  } else if (object && typeof object === 'object') {
    return assign(Object.create(Object.getPrototypeOf(object)), object);
  } else {
  ...
```

`Object.getPrototypeOf` satisfies all three cases, `null` when lacking prototype, prototype object when prototyping, and constructor function for derived objects.

**Comment by kolodny** [comment]
Awesome, Thanks for the issue and the fix. I'm published the updated library with the fix to `v2.7.1`
