### ISSUE TITLE
ESlint warnings (create-react-app application)

### ISSUE THREAD

**Issue by kadoshms** [kolodny/immutability-helper#110]
Hey there,

I am working on a CRA app and the console keeps throwing these warnings:

> ./src/modules/core/node_modules/immutability-helper/index.js
>   Line 72:  'index' is defined but never used  no-unused-vars
>   Line 72:  'key' is defined but never used    no-unused-vars
>   Line 85:  Unexpected mix of '||' and '&&'    no-mixed-operators
>   Line 85:  Unexpected mix of '||' and '&&'    no-mixed-operators
> 
> 

Thanks :)

**Comment by kolodny** [comment]
I believe node_modules should be ignored for eslint. Do you have repro steps?

**Comment by kolodny** [comment]
Closing for now, feel free to reopen if this is still an issue
