### ISSUE TITLE
PhpStorm/Webstorm performance 2.8.0+

### ISSUE THREAD

**Issue by kucix** [kolodny/immutability-helper#115]
Hi,
after update to 2.8.x version, our IDE (PhpStorm and Webstorm) is consuming about 60-90% of CPU and hangs allmost on every action with .ts and .tsx files.

If we downgrade immutability-helper to 2.7.1, everything works fine and smooth, IDEs consuming about 0-5% of CPU

The only change is in package.json in version of immutability-helper, nothing else.

**Comment by kolodny** [comment]
Hi @kucix I'm not able to repro, can you share a minimalistic repro case. Please include the tsconfig file as well. Thanks

**Comment by kucix** [comment]
Hi,
I couldn't determine whats wrong.
If I write simple reducer, everything is ok.
If I paste our reducer with 40-50 update calls, things getting slow.
If I paste 50 or more simple update calls, everything is OK..
I don't know where the problem is.
We using almost all commands.
Reducer is not simple $set whats we get from payload, but there is some logic inside reducer.

Pasting our reducer here is problematic, it is closed source, our company code.

I know, that You couldn't fix what You can't simulate, so maybe we stay on 2.7.1 and You close this issue.
Maybe someone else will have this problem too and can create test scenario.

tsconfig
```
{
  "compilerOptions": {
    "allowJs": true,
    "checkJs": true,
    "outDir": "./dist/",
    "sourceMap": true,
    "module": "commonjs",
    "target": "es5",
    "jsx": "react",
    "alwaysStrict": true,
    "removeComments": true,
    "strictNullChecks": true,
    "lib": [
      "DOM",
      "ES7",
      "es2015",
      "es2018",
      "ScriptHost",
      "esnext.asynciterable"
    ]
  },
  "include": [
    "./src/**/*"
  ]
}
```

**Comment by kolodny** [comment]
Closing for now. I'll reopen if other start experiencing this issue as well
