### ISSUE TITLE
TypeScript - type checks prevent from updating with a different type

### ISSUE THREAD

**Issue by code-hunger** [kolodny/immutability-helper#119]
**Example code:** I have an object containing a number and I want to replace the number with `undefined` (in my tests, to see if my app will crash):

    update({ x: 0 }, { x: { $set: undefined }});

**Current behaviour:** instead of an object with `x` being `undefined`, I get a type error saying that `$set` expects a number.  

**Expected behaviour:** `update()` returns a new object whose type properly reflects the changes in the passed updater object.  
Replacing `undefined` with other types of values also gives this error.

---
I guess it might be impossible in TypeScript to infer the type of the new object from the type of the old value and the type of the updater object, but I can't be sure.

**Comment by kolodny** [comment]
Would it make more sense to use [`$unset`](https://github.com/kolodny/immutability-helper#available-commands)?

**Comment by kolodny** [comment]
I also think you would need to be more explicit it the State interface:

```js
const state: {x?: number} = {
  x: 0,
};
const updated = update(state, {$set: undefined});
updated.x
```

But I don't think that this library could infer new interface shapes based on directives. @andreiglingeanu may know if it's possible

![image](https://user-images.githubusercontent.com/1187604/48682307-a8c53e80-eb75-11e8-9a78-03761e4c46ea.png)

**Comment by andreiglingeanu** [comment]
Actually there is some inferring in place and it _does_ work for you -- that's why you're not allowed to swap `0` with `undefined`, because those values have different types.

And yeah, a good work around would be more explicitness when declaring state type

**Comment by code-hunger** [comment]
I'm sorry I caused this confusion, I never thought about `$unset`, that it could be used to make something `undefined`.

Andreiglingeanu is right - `undefined` and my state variable have different types because my state variable type does not allow null/undefineds.

What I was trying to do was test my code for proper null-handling, because I was getting tired of receiving at run time `undefined`s where the type did not allow it.  
Now that I'm thinking about it again, I'm not sure anymore it makes sense to have such tests, because it is responsibility of the outer code to send non-null values where undefineds are unexpected.

Thanks for your replies!
