### ISSUE TITLE
Pass original object to command

### ISSUE THREAD

**Issue by Robinfr** [kolodny/immutability-helper#121]
Would it be possible to pass the original object that was initially passed to `update` down to the command as the fifth argument? E.g. for creating commands like `$copy` that clone a part of the object.

**Comment by kolodny** [comment]
Seems like this can get out of hand but other than that I can't give you a good reason why not. What are other folks thoughts?

**Comment by jednano** [comment]
I want to see an example implementation to see why this is needed. Adding more arguments to a function is a code smell, especially anything more than three arguments.

**Comment by kolodny** [comment]
Closing for now. Feel free to reopen if you feel strongly about it (and provide an example that @jedmao asked for)
