### ISSUE TITLE
Add positional operator

### ISSUE THREAD

**Issue by Andreyco** [kolodny/immutability-helper#125]
Add positional operator in order to update items in collection in simple and declarative manner.

```
const users = [
  { id: 1, name: 'Andrej', surname: 'Badin' },
  { id: 2, name: 'John', surname: 'Doe' },
];

const patchedUsers = { id: 2, surname: 'Appleseed' };

const updatedUsers = update(users, { $: { $merge: patchedUsers } });

// Expected output
// const updatedUsers = [
//   { id: 1, name: 'Andrej', surname: 'Badin' },
//   { id: 2, name: 'John', surname: 'Appleseed' },
// ];
```

I am open to operator name, it could be `$`, `$_`, `$pos`, `$idx` or whatever.

Prop used to find item position in collection could be specified if not default (`id` prop?), e.g.

```
const updatedUsers = update(users, { $: { $merge: patchedUsers, identifier: 'key' } });
```

Nice to have:
- update multiple items in collection at once (could be possible if `identifier` is function which return boolean when `update` searches for matched items)

**Comment by jednano** [comment]
Like [`_.find`](https://lodash.com/docs/4.17.11#find), you would have to somehow specify the predicate for how to find the right item:
```ts
const predicate = { id: 2 };
const predicate = user => user.id === 2;
```
Where to provide the predicate, I'm not sure.

**Comment by Andreyco** [comment]
For now, I have implementation for this API.

```javascript
describe('$pos', function () {
  it('updates all items', function() {
    var collection = ['a', 'b'];
    expect(update(collection, {$pos: {$set: 'c'}})).toEqual(['c', 'c']);
  });
  it('updates item at position specified by index', function() {
    var collection = ['a', 'a'];
    expect(update(collection, {$pos: {$index: 1, $set: 'b'}})).toEqual(['a', 'b']);
  });
  it('updates item at position specified by query', function() {
    var collection = [{ id: 1, name: 'John'}, { id: 2, name: 'Mark'}];
    var expectedCollection = [{ id: 1, name: 'John'}, { id: 2, name: 'Andrej'}];
    var spec = { $query: obj => obj.id === 2, name: { $set: 'Andrej' }};
    expect(update(collection, {$pos: spec})).toEqual(expectedCollection);
  });
})
```

Not sure whether I like `$index` and `$query` params for spec but somehow items needs to be matched...

Feedback is appreciated.

**Comment by kolodny** [comment]
For changing an item in an array I would suggest using the map method, an not using this library at all. For the use case you have above, something like this:

```js
const users = [
  { id: 1, name: 'Andrej', surname: 'Badin' },
  { id: 2, name: 'John', surname: 'Doe' },
];

const patchedUser = { surname: 'Appleseed' };

const patchedUsers = users.map(
    user => user.id === 2 ? update(user, {$merge: patchedUser}) : user)
console.log(JSON.stringify(patchedUsers, null, 2));

/*
[
  {
    "id": 1,
    "name": "Andrej",
    "surname": "Badin"
  },
  {
    "id": 2,
    "name": "John",
    "surname": "Appleseed"
  }
]
*/
```

**Comment by joelkraft** [comment]
Would it be helpful to consider a positional operator (or expression) for deeply nested objects? I agree using map for 1 level makes a bit more sense, but what about an object like the following:

```javascript
const stateTree = {
    listOfObjects: [
        {
            id: 0,
            prop: 'Easy to map to',
            firstLevelDeeper: [
                {
                    id: 1,
                    someProp: 'O hi there',
                    secondLevelDeeper: [
                        {
                            id: 3,
                            someOtherProp: 'Nested safely',
                            thirdLevelDeeper: [
                                {
                                    id: 6,
                                    deeplyNestedProp: 'Change me'
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]
}

const patch = { deeplyNestedProp: { $set: 'Updated!'} }
```
You could do
```javascript
const patchedStateTree = {
    ...stateTree,
    listOfObjects: stateTree.listOfObjects.map(topLevel =>
        topLevel.id === 0
            ? {
                  ...topLevel,
                  firstLevelDeeper: topLevel.firstLevelDeeper.map(firstLevel =>
                      firstLevel.id === 1
                          ? {
                                ...firstLevel,
                                secondLevelDeeper: firstLevel.secondLevelDeeper.map(
                                    secondLevel =>
                                        secondLevel.id === 3
                                            ? {
                                                  ...secondLevel,
                                                  thirdLevelDeeper: secondLevel.thirdLevelDeeper.map(
                                                      thirdLevel =>
                                                          thirdLevel.id === 6
                                                              ? update(thirdLevel, patch)
                                                              : thirdLevel
                                                  )
                                              }
                                            : secondLevel
                                )
                            }
                          : firstLevel
                  )
              }
            : topLevel
    )
}
```
For my project, I went through and found all the indexes first, which works, though it seems like the goal of this library is to alleviate the kind of code above.
Would it make sense, for example to allow some sort of expression for keys, such as the following:
```javascript
 const altPatch = {
    listOfObjects: {
        '[id: 0]': {
            firstLevelDeeper: {
                '[id: 1]': {
                    secondLevelDeeper: {
                        '[id: 3]':{
                            thirdLevelDeeper: {
                                '[id: 6]':{
                                    deeplyNestedProp: { $set: 'Updated!'}
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
```
There could be a way to configure the `[]`s to use some other character to indicate the need to iterate, in case a project is using those in their keys for some reason.

Perhaps there is a better way that I haven't thought of here! I'm open to ideas. I recognize this would add some complexity to the simplicity of this tool, but I'm curious if anyone thinks it might be worth it.

**Comment by kolodny** [comment]
I'm not sure I follow what you're trying to do. Do you not know the path to the object ahead of time? Are there multiple copies of the same thing that need to be updated?

**Comment by joelkraft** [comment]
Sorry I wasn't clear. In my example I know the way to the target object by `id` property values, but not necessarily their array indices. For each array, I'm mapping to identify the object, then going deeper to the next nested array. It seems like this library is designed for those who know their way to a nested object by array position, but not by object property value (ex. `id`), which I would think would be a common use case for updating state.

Does that make sense? The example I'm talking about is essentially carrying the example given by @Andreyco further, to show how verbose and unreadable things can get as arrays of objects are nested (at least the way I'm doing them.. I may be missing out on a better way!).

**Comment by kolodny** [comment]
I think that's out of scope for this library. It may be worth writing a function to compute the spec object needed for what you're trying to do and use that in tandem with this library
