### ISSUE TITLE
$set ignores properties defined with Object.defineProperty

### ISSUE THREAD

**Issue by fabb** [kolodny/immutability-helper#131]
Suppose we have an object that contains a property defined with `Object.defineProperty`:

```js
function MyObj() {
    this.settings = {
        value: "",
        sideEffect: ""
    }
    Object.defineProperty(this, "myProp", {
        get: function() {
            return JSON.parse(JSON.stringify(this.settings.value))
        },
        set: function(settings) {
            this.settings.value = JSON.parse(JSON.stringify(settings))
            this.settings.sideEffect = JSON.parse(JSON.stringify(settings))
        }
    })
}

let m = new MyObj()
let objs = {
    m: m
}

objs.m.myProp = "asdf"
document.write("<pre>" + JSON.stringify(objs.m, null, 2))
document.write("<pre>" + JSON.stringify(objs.m.myProp, null, 2))

const newObjs = update(objs, { m: { myProp: { $set: "qwer" } } })
document.write("<pre>" + JSON.stringify(newObjs.m, null, 2))
document.write("<pre>" + JSON.stringify(newObjs.m.myProp, null, 2))
```

Output:

```js
{
  "settings": {
    "value": "asdf",
    "sideEffect": "asdf"
  }
}
"asdf"
{
  "settings": {
    "value": "asdf",
    "sideEffect": "asdf"
  },
  "myProp": "qwer"
}
"qwer"
```

https://codesandbox.io/s/q9pq0z3z26

As seen from the output, `update` ignores that there is already a property with name `myProp` defined on the instance of `MyObj`, and it rather just adds a new field to the instance. This is not ideal, I would expect `update` to use the setter of `myProp` to set the new value.

**Comment by fabb** [comment]
Even when this should be out of scope for this library, at least add a warning to the readme?

**Comment by kolodny** [comment]
[This doesn't work using `Object.assign`.](https://stackblitz.com/edit/js-vfjgwx?file=index.js) This falls under what I call "runtime magic", this library can't handle every edge case. The biggest issue with how to deal with this is to clone the object with saving the all getters and setters. It would entail replaying all the `Object.getOwnPropertyDescriptors` and running those on the object, I have no idea what that would do to the runtime but it would (presumably) greatly affect the performance of this library. I'm open to solutions if there's something I'm missing (or a PR to add some warning in the readme)

**Comment by fabb** [comment]
Maybe just add a warning to the readme?

**Comment by kolodny** [comment]
I'm open to a PR but I don't really think there needs to be a giant warning note or anything. I'm not sure what the exact wording should be though

**Comment by fabb** [comment]
Something like this? #132
