### ISSUE TITLE
Bootstrap package removed after installing immutability-helper

### ISSUE THREAD

**Issue by padmano** [kolodny/immutability-helper#134]
I use bootstrap package from [here](https://www.npmjs.com/package/bootstrap).

Once I installed immutability-helper, boostrap package gets removed

![image](https://user-images.githubusercontent.com/2375346/51257548-dab81d00-19cd-11e9-94ba-54272355c4a8.png)

 Had to install bootstrap again.

**Comment by kolodny** [comment]
This sounds like a weird package-lock.json. Can you provide steps to repro from an empty project?

**Comment by jednano** [comment]
I agree. There's nothing in this package (or any package) that would be removing other packages. Try `npm install` w/o installing immutability-helper and see if you have the same problems.

**Comment by padmano** [comment]
@kolodny steps to reproduce:

1. Install Bootstrap using `npm i bootstrap` from [here](https://www.npmjs.com/package/bootstrap).
2. Install immutability-helper using `npm install immutability-helper --save` as shown [here](https://github.com/kolodny/immutability-helper).

**Comment by kolodny** [comment]
Running this seems to work fine

```bash
mkdir removed-bootstrap && cd removed-bootstrap && npm init -y && npm i bootstrap && npm install immutability-helper --save && ls node_modules/bootstrap
```

**Comment by padmano** [comment]
@kolodny  yes it does. But the issue persists when I do `npm install immutability-helper --save` to a project that already has bootstrap installed and adding immutability-helper as a new dependency.

**Comment by kolodny** [comment]
But that's what the snippet above does and bootstrap is still there. Am I missing something?

**Comment by jednano** [comment]
Maybe an older version of Bootstrap? @iamTheL what version of Bootstrap do you have installed? And does updating your Bootstrap version before you install `immutability-helper` solve the issue?

**Comment by kolodny** [comment]
Closing for now, feel free to reopen if there's anything actionable to do in this repo
