### ISSUE TITLE
Doesn't seem to carry over properties that being with _

### ISSUE THREAD

**Issue by akeemphilbert** [kolodny/immutability-helper#14]
If I have an object 
`{ _id: "123",_rev:"123",budget:0,title:"abc"}`

and I do 
`update(task,{budget: {$set:123}})`

I get 
`{_id:undefined, _rev:undefined, budget:123, title:"abc"}`

**Comment by kolodny** [comment]
It seems to work for me, paste the following into http://requirebin.com/

```js
var update = require('immutability-helper');
var task = { _id: "123",_rev:"123",budget:0,title:"abc"};
document.write('<pre>' + JSON.stringify(    update(task,{budget: {$set:123}})     , null, 2))
```

Here's what I get
![image](https://cloud.githubusercontent.com/assets/1187604/22230076/9e067018-e1a9-11e6-84d0-f494ec46701a.png)
