### ISSUE TITLE
Error in type or realization

### ISSUE THREAD

**Issue by snatvb** [kolodny/immutability-helper#142]
Example:  
```typescript
import update from 'immutability-helper'

const test: {
  messages?: {
    [id: string]: string[],
  },
} = {}

const newState = update(test, {
  messages: {
    '1': { $set: [] },
  }
})
console.log(newState)
```

Error:  
```js
Cannot read property '1' of undefined 
  at ​./node_modules/immutability-helper/index.js:79​
  at ​​​Context.update​​​ ​./node_modules/immutability-helper/index.js:68​
  at ​./node_modules/immutability-helper/index.js:79​
  at ​​​Context.update​​​ ​./node_modules/immutability-helper/index.js:68​
  at ​​​Object.<anonymous>​​​ ​quokka.ts:9:0​
  at ​​​Module._compile​​​ ​internal/modules/cjs/loader.js:689
```

Typescript says that this is ok.
Where error?

**Comment by kolodny** [comment]
Typescript has no way of knowing that the optional value is not set on the original object. This is more of a runtime error and that error is: you can't set properties on objects that are non existent. This is similar to this error

```ts
const test: {
  messages?: {
    [id: string]: string[],
  },
} = {}

test.messages[1] = []; // error: Cannot set property '1' of undefined
```

**Comment by jednano** [comment]
You might be interested in [`just-safe-set`](https://www.npmjs.com/package/just-safe-set) or [`_.set`](https://lodash.com/docs/4.17.11#set).

Also, you can define `{ [id: string]: string[] }` as `Record<string, string[]>` in TypeScript.

**Comment by snatvb** [comment]
@jedmao nope, i need normal types, i made fork and add that i need
