### ISSUE TITLE
Array length not updating

### ISSUE THREAD

**Issue by anushkadoyan** [kolodny/immutability-helper#144]
When I unset/push items in my state, the array length does not update. For example, if I unset the only element in an array, the array comes back empty with length 1. 

`this.setState({attributes: update(this.state.attributes, {$unset: [i]})});`

**Comment by kolodny** [comment]
We don't modify the return type of the function. If we would we should first return `T & { $setValue }` for a set operation. Note that what you're describing is a TS issue more than anything else:

https://www.typescriptlang.org/play/#src=const%20a%3A%20%5Bnumber%5D%20%3D%20%5B1%5D%3B%0D%0Aa.push(1)%3B%0D%0Aa

Closing for now, feel free to reopen if anything isn't clear

**Comment by anushkadoyan** [comment]
I don't mean the type, if I unset an element from an array it will change the array contents but the length property will remain the same

**Comment by kolodny** [comment]
Gotcha, that would be even trickier to handle since the array length doesn't actually change and instead the array element is just set to undefined.

Also `var a = ['x', 'y', 'z']; delete a[2]; a.length` returns 3 as well
