### ISSUE TITLE
Add $increaseBy and $decreaseBy

### ISSUE THREAD

**Issue by blaues0cke** [kolodny/immutability-helper#145]
Just got this case. Would be nice to be able to do this:

    return update(state, {
        isDragging: {
            $set: true
        },
        operationCounter: {
            $increaseBy: 1
        }
    });

instead of

    return update(state, {
        isDragging: {
            $set: true
        },
        operationCounter: {
            $set: state.operationCounter + 1
        }
    });

**Comment by kolodny** [comment]
This is already possible to do by [adding some commands to the function](https://github.com/kolodny/immutability-helper#adding-your-own-commands):

```js
import update from 'immutability-helper';

update.extend('$increaseBy', (amount, value) => value + amount);
update.extend('$decreaseBy', (amount, value) => value - amount);

const state = {
  num1: 10,
  num2: 20,
  num3: 30,
};
const updated = update(state, {
  num1: {$increaseBy: 5},
  num2: {$decreaseBy: 7},
});
console.log(updated); // {num1: 15, num2: 13, num3: 30}
```

The typings isn't quite able to handle these but [they work just fine](https://stackblitz.com/edit/typescript-wdnt4m)

**Comment by blaues0cke** [comment]
Thank you! Sorry, did not had the idea to just use `.extend`. Still a "basic enough" feature or should I close this here?

**Comment by kolodny** [comment]
We can leave it open for a bit to see if folks 👍 it and if so consider adding it to the default command set, Otherwise I'd close it after a couple of days
