### ISSUE TITLE
Use splice instead of the delete keyword when using unset on arrays

### ISSUE THREAD

**Issue by expenses** [kolodny/immutability-helper#147]
`delete array[index]` leaves a gap in the array. Using `array.splice(index, 1)` would be better.

**Comment by kolodny** [comment]
Where is delete being used? The example on the readme is using splice https://github.com/kolodny/immutability-helper#removing-an-element-from-an-array

**Comment by expenses** [comment]
I'm talking about the code here: https://github.com/kolodny/immutability-helper/blob/master/index.ts#L166. I just think that we should use `splice` not delete as that is commonly what people want. See https://stackoverflow.com/a/500617/4286206

**Comment by kolodny** [comment]
Unset is meant to be used on objects, not arrays
