### ISSUE TITLE
update changes keys to undefined

### ISSUE THREAD

**Issue by agniveshadhikari** [kolodny/immutability-helper#148]
```
update(acc, {
        [time]: {
          $set: { "value": "data" }
        }
      })
```

This is the update call from a MWE that inexplicably returns objects with key 'undefined' rather than 'value'
![image](https://user-images.githubusercontent.com/23560829/63931253-8c462300-ca72-11e9-8539-962b352c36e0.png)

In fact, the first few calls work as expected
![image](https://user-images.githubusercontent.com/23560829/63931508-08d90180-ca73-11e9-9818-791ccf3f56c3.png)
, but then it starts setting undefined
![image](https://user-images.githubusercontent.com/23560829/63931561-27d79380-ca73-11e9-9f8b-d8221ed3820a.png)
, and by the end of my reduce, all the keys are undefined, as shown in the first image.

**Comment by kolodny** [comment]
Can you provide a reproducible example of this happening?
