### ISSUE TITLE
Can't push to array of {}

### ISSUE THREAD

**Issue by abriginets** [kolodny/immutability-helper#149]
Hello. Currently I'm struggling while trying to change my React component's state. Basically I have something like this:

```
var obj = {
  segments: [{
    foo: 'bar',
    bar: 'baz'
  }]
}
```
And I have an array:
```
var newSegmentsToAdd = [{
  baz: 'foo'
},
{
  foo: 'foo'
}]
```

I'm trying to merge two arrays:

```
var newData = update(obj, {
  segments: { $push: newSegmentsToAdd }
})
```

This few lines of code gives me that much errors in console and I can barely understand what is happening:

> error TS2345: Argument of type '{ segments: { $push: ({ baz: string; foo?: undefined; } | { foo: string; baz?: undefined; })[]; }; }' is not assignable to parameter of type 'Spec<{ segments: { foo: string; bar: string;}[]; }, never>'.
>   Type '{ segments: { $push: ({ baz: string; foo?: undefined; } | { foo: string; baz?: undefined; })[]; }; }' is not assignable to type '{ segments?: { $push: { foo: string; bar: string; }[]; } | { $unshift: { foo: string; bar: string;}[]; } | { $splice: ([number, (number | undefined)?] | [number, number, ...{ foo: string; bar: string; }[]])[]; } | ... 4 more ... | undefined; }'.
>     Types of property 'segments' are incompatible.
>       Type '{ $push: ({ baz: string; foo?: undefined; } | { foo: string; baz?: undefined; })[]; }' is not assignable to type '{ $push: { foo: string; bar: string; }[]; } | { $unshift: { foo: string; bar: string; }[]; } | { $splice: ([number, (number | undefined)?] | [number, number, ...{ foo: string; bar: string; }[]])[]; } | { [index: string]: Spec<{foo: string; bar: string; }, never>; } | { ...; } | { ...;} | ((v: { ...; }[]) => { ...;...'.
>         Type '{ $push: ({ baz: string; foo?: undefined; } | { foo: string; baz?: undefined; })[]; }' is not assignable to type '{ [index: string]: Spec<{ foo: string; bar: string; }, never>; }'.
>           Property '$push' is incompatible with index signature.
>             Type '({ baz: string; foo?: undefined; } | { foo: string; baz?: undefined; })[]' is not assignable to type 'Spec<{ foo: string; bar: string; }, never>'.
>               Type '({ baz: string; foo?: undefined; } | {foo: string; baz?: undefined; })[]' is not assignable to type '(v: { foo: string; bar: string; }) => { foo: string; bar: string; }'.
>                 Type '({ baz: string; foo?: undefined; } |{ foo: string; baz?: undefined; })[]' provides no match for the signature '(v: { foo: string; bar: string; }): { foo:string; bar: string; }'

Am I trying to do something that is not supposed to be done?

Here's a [Repl](https://repl.it/@JamesJGoodwin/SpeedyCrookedParticle) to reproduce it

**Comment by jednano** [comment]
TypeScript doesn't take kindly to pushing objects onto an array that don't match the array type. Your first segment is of type `{ foo: string; bar: string }` so TS assumes (and rightly so) that any future objects you push will be of the same type. You can fix this by being more explicit about the structure of your array:

```ts
const obj: {
  segments: ({
    foo?: string;
    bar?: string;
    baz?: string;
  })[]
} = {
  segments: [{
    foo: 'bar',
    bar: 'baz'
  }]
}
```
Then you can push safely what you tried above. Works fine on [the repl](https://repl.it/repls/AlertConfusedInterfacestandard).

**Comment by jednano** [comment]
If you don't know the type of the array ahead of time you can use an excess property check to allow everything like:

```ts
interface Segment {
    foo?: string;
    bar?: string;
    [key: string]: string; // or another type or `any`
}
```

**Comment by abriginets** [comment]
Sorry for creating non-module-related issue. It looks like TypeScript misinterpreted the types and I simply fixed it by adding interface type to my variable and it worked.
