### ISSUE TITLE
Type definition for $set parameter should be Partial<T> not T?

### ISSUE THREAD

**Issue by slawiko** [kolodny/immutability-helper#151]
I have following snippet:

```typescript
let changedNode: { variable?: string, anotherThing: number } = node;

if (node.variable) {
    changedNode = update(changedNode, {
        variable: { $set: 'someString' },
    });
}
```

And I receive following error:
`Assigned expression type {variable: string} is not assignable to type {variable?: string, anotherThing: number} `

Which is logical:  `$set` waits for `T` type.

Shouldn't it wait for `Partial<T>`?

**Comment by kolodny** [comment]
This seems to work for me: https://stackblitz.com/edit/typescript-1qqsgh?file=index.ts

**Comment by slawiko** [comment]
Sorry, I didn't realise that I used version 2 and @types package. With version 3 everything works fine, thanks!
