### ISSUE TITLE
When use $set to set a string with spaces, it doesn't works 

### ISSUE THREAD

**Issue by dengxiao0509** [kolodny/immutability-helper#152]
e.g.

const obj = {a: '123'}

const obj2 = update(obj, {
    a: {
          $set: '123   ',
    }
})

console.log(obj === obj2)    // true

It seems that helper considers '123' is equal to '123  '? But that results in failing getting a new obj reference, any solution?

**Comment by kolodny** [comment]
This seems to be working as expected in runkit: https://runkit.com/embed/mq5zkzqv3y2z

![image](https://user-images.githubusercontent.com/1187604/75883826-aaaa2400-5df1-11ea-84a6-9cbfa49c3148.png)
