### ISSUE TITLE
readme: missing brackets around array index?

### ISSUE THREAD

**Issue by stuartcrobinson** [kolodny/immutability-helper#160]
should:

`update(collection, {2`...

be

`update(collection, {[2]`...

here, in the readme:

```
Nested collections

const collection = [1, 2, {a: [12, 17, 15]}];
const newCollection = update(collection, {2: {a: {$splice: [[1, 1, 13, 14]]}}});
// => [1, 2, {a: [12, 13, 14, 15]}]
```

?

**Comment by kolodny** [comment]
Either usage works, not really a typo. Open to a PR if it bothers you but closing this issue in the meantime
