### ISSUE TITLE
Exported MapSpec type does not allow specs in typescript which seem to work correctly in JS

### ISSUE THREAD

**Issue by semicoleon** [kolodny/immutability-helper#161]
Version: 3.0.2
Typescript: 3.7.5

The example code [in this comment](https://github.com/kolodny/immutability-helper/pull/103#issuecomment-382234122) (shown below) does not compile in typescript.

```typescript
var state = new Map([
    ['mapKey', { banana: 'yellow', apple: ['red'], blueberry: 'purple', obj: {a:true} }]
]);

var updatedState = update(state, {
    ['mapKey']: {
        apple: { $set: ['green', 'red'] },
        obj: {$toggle: ['a']}
    }
});
```

tsc error:
```
Type '{ apple: { $set: string[]; }; obj: { $toggle: string[]; }; }' is not assignable to type '{ $set: { banana: string; apple: string[]; blueberry: string; obj: { a: boolean; }; }; }'.
  Object literal may only specify known properties, and 'apple' does not exist in type '{ $set: { banana: string; apple: string[]; blueberry: string; obj: { a: boolean; }; }; }'
```

Since the object is a literal the error is kind of verbose, but the tl;dr is that typescript thinks the $set command can only accept a value of the same type as the Map's value type, and not additional commands operating on the current value in the map.

Running the sample code in a plain JS environment (or presumably by forcing update to use `any` as the spec type) produces the expected result, so I think this is strictly a problem with the exported typescript types.

It's also possible typescript is inferring a type weirdly, but I'm not sure what I would need to change to make it work correctly.

**Comment by semicoleon** [comment]
Just [replacing the $set portion of MapSpec with another full Spec](https://github.com/kolodny/immutability-helper/compare/master...colekurk:typescript-map-fix) does seem to resolve this. I'm not entirely confident that's the *most* correct answer, but at the very least it does get rid of the error.

**Comment by kolodny** [comment]
I'd be open for a PR
