### ISSUE TITLE
Supporting cyclic state

### ISSUE THREAD

**Issue by shayantabrizi** [kolodny/immutability-helper#163]
If the state has directional cycles  (a-->b-->c-->a, in which _a_, _b_, and _c_ are objects; and a-->b denotes that _a_ has a reference to _b_), or undirectional cycles (a-->b-->c and a-->d-->c), can immutability-helper handle that correctly? (In the first example, changing _a.b.c.a_ also changes _a_, and in the second example, changing _a.b.c_ also changes _a.d.c_)

**Comment by kolodny** [comment]
I would play around to verify your use case is covered but the quick answer is that the update function will spread over an object before it makes mutations so any references should be lost. Of course if a property of the object is a reference than that reference will remain
