### ISSUE TITLE
Is updatePath still feature of this package?

### ISSUE THREAD

**Issue by NikDm** [kolodny/immutability-helper#169]
I really need updatePath feature so I can push item to deep nested array by string path.
But I can't seem to get it working. Am I doing something wrong or updatePath is no more?

**Comment by kolodny** [comment]
I don't understand, what's the updatePath feature?

**Comment by GuYounes** [comment]
Hi, I think he talks about the feature explained in this comment: https://github.com/kolodny/immutability-helper/issues/64#issuecomment-333867524

I also would need it and I think it would be a useful feature.
