### ISSUE TITLE
Dot notation support

### ISSUE THREAD

**Issue by DaddyWarbucks** [kolodny/immutability-helper#17]
The MongoDB query language supports dot notion. For example:
```
db.jobs.find({"customer.first_name": someValue});
```
I see that immutability helper supports the Mongo commands, but dot notation does not seem be supported. Is that correct?

For example, the following code updates a a property `customer.first_name` on the root of `job`, rather than finding/updating `job.customer.first_name`.
```
update(job, {"customer.first_name": {$set: someValue}})
```

I understand that I could manually drill down to the the proper place. But, what I am really trying to do is use a variable representing the location of the value to update

For example: 
```
// inputData = {name: "customer.first_name", value: "John"}
// inputData = {name: "address.zip", value: "12345"}
update(job, {`${inputData.name}`: {$set: inputData.value}});
```

I am I understanding properly that `immutability-helper` does not support dot notation as stated?

Thanks!!

**Comment by kolodny** [comment]
`immutability-helper` doesn't support that. It would be difficult to know if you wanted to edit a property on the object `obj['customer.first_name']` or if you wanted to drill down `obj.customer.first_name`

**Comment by DaddyWarbucks** [comment]
Understood. Thank you for the clarification!

**Comment by hoytech** [comment]
I have added an `updatePath` function to update-immutable that supports dot-separated lists of keys. You can read its documentation along with a few examples here:

https://www.npmjs.com/package/update-immutable#updatepath

**Comment by DaddyWarbucks** [comment]
Well done! Thanks for this!

**Comment by hoytech** [comment]
Thanks! The feature is still experimental so if you give it a try, let me know if there's anything missing/buggy.
