### ISSUE TITLE
Typescript errors when trying to modify spec that both sets array element and pushes

### ISSUE THREAD

**Issue by smhsu** [kolodny/immutability-helper#174]
Hello,

I have a spec that both sets an array element and pushes a new one. As a contrived example,
```
const testSpec: Spec<number[]> = {
    0: { $set: 5 },
    $push: [ 6 ]
};
```
Typescript seems happy with the above.

But when I try to modify this spec in subsequent code...
```
testSpec[0] = { $set: 5 };
^ Element implicitly has an 'any' type because expression of type '0' can't be used to index type 'Spec<number[], never>'.
  Property '0' does not exist on type 'Spec<number[], never>'

testSpec.$push = [ 6 ];
^ Property '$push' does not exist on type 'Spec<number[], never>'.
  Property '$push' does not exist on type '{ $unshift: readonly number[]; }'.  TS2339
```

What am I doing wrong here? Or is it a bug? Any help would be appreciated.

**Comment by kolodny** [comment]
[I can't seem to repro](https://stackblitz.com/edit/typescript-glbvmn), can you create a stackblitz or something similar with the issue?
