### ISSUE TITLE
Documentating syntax for arrays (e.g. updating items within a multidimensional array)?

### ISSUE THREAD

**Issue by tog22** [kolodny/immutability-helper#175]
Can you give the syntax for arrays?

For example, if I have the array `mdarray: [[1,2],[3,4]` then how do I update the value of mdarray[0][0]? The documentation only covers changing nested properties of object like myData.x.y.z.

**Comment by kolodny** [comment]
```
const mdarray = [[1,2],[3,4]];

const mdarray2 = update(mdarray, {
  0: {
    0: {$set: 5},
  }
})

console.log(mdarray2) // [ [ 5, 2 ], [ 3, 4 ]
```
