### ISSUE TITLE
$set is not working for setting properties deep in object.

### ISSUE THREAD

**Issue by DhruvPatel3** [kolodny/immutability-helper#176]
**Concern by example:-**
```
//Where $set doesn't work
 
const obj1 = {b: 'b'};

const newObj1 = update(obj1, {
   d: {
         e: { 
                $set: "e",
            },
       },
});

//Shouldn't this be handled out of the box?

//=========================================

//where it works 

const obj2 = {b: 'b', d: { f: 'f' }};

const newObj2 = update(obj2, {
   d: {
         e: { 
                $set: "e",
            },
       },
});

```

**Detailed Expression:-**

I am not sure this would be a bug report or a feature request and if anyone has encountered the following use case yet. But can someone please suggest a better way to handle the following scenario?
There can be a case where we try to set a property deep in an object and the parent object where we want to set this property can be undefined too.
So in a case where the parent object is defined the $set will work correctly but if it is undefined, update of immutability helper will throw an error. [Here](https://codesandbox.io/s/error-with-immutability-helper-wddpb?file=/src/App.tsx) is a link of codesandbox to demonstrate the concern.
There can be multiple level of nesting so we cannot actually check at every level if this property exists or not and depending on that apply $set or $merge at appropriate level.

**Comment by kolodny** [comment]
You should be setting the closest actual property in that case

```ts
const newObj3 = update(obj2, {
  d: {$set: {e: 'e'} as any},
});
```

As to why that is, see https://github.com/kolodny/immutability-helper/issues/16#issuecomment-289326983 for more details
