### ISSUE TITLE
Nested $merge does not seem to work

### ISSUE THREAD

**Issue by dakur** [kolodny/immutability-helper#19]
Hi,

maybe I'm missing something, but I'm not able to run this:
```
import update from 'immutability-helper';

let state = {
	isValid: null,
	isVisible: false,

	set: {
		isValid: null,
		isVisible: false,

		distance: {
			isValid: null,
			isVisible: false
		},
		hours: {
			isValid: null,
			isVisible: false
		}
	}
};

update(state, {
	set: {
		$merge: {
			isVisible: activity !== null && activity !== '',

			distance: {
				$merge: {
					isVisible: activity === 'bike' || activity === 'run'
				}
			},
			hours: {
				$merge: {
					isVisible: activity === 'other'
				}
			}
		}
	}
)
```

The output of update method is:
![snimek z 2017-02-07 08-58-38](https://cloud.githubusercontent.com/assets/9862581/22682584/ac156dc4-ed13-11e6-9eab-d971237bb10d.png)

So the nested merge does not parse. Is this a bug, or a feature?

Thank you,
dakur

**Comment by kolodny** [comment]
There currently isn't any way to do something like this built in. The reason for that it should be possible to use a command like `$set` to make the value be `{$set: ...}`. Consider this
```js
var state = {a:1}
var next = update(state, {
  a: {
    $set: {
      $set: 1
    }
  }
})
```

Practically speaking the commands are black boxes that don't look deeply into the values passed to them. In order to do what you suggest, you would need `$merge` to know it needs to be recursive.

**Comment by dakur** [comment]
Yep, thank you very much, I've probably misused `$merge`. `$set` is much better. Rewritten to:
```
update(state, {
	set: {
		isVisible: {
			$set: action.activity !== null && action.activity !== ''
		},

		distance: {
			isVisible: {
				$set: action.activity === 'bike' || action.activity === 'run'
			}
		},
		hours: {
			isVisible: {
				$set: action.activity === 'other'
			}
		}
	}
});
```
and works great.
