### ISSUE TITLE
Swapping values of a nested array

### ISSUE THREAD

**Issue by safm** [kolodny/immutability-helper#20]
I am trying to swap values of an array based on index. Below is scaled down version of my code. 
The index values will be dynamic.

```Javascript
const s = [ [ 1, 2, 3, 4 ] ]

const v1= s[ 0 ][ 1 ];
const v2 = s[ 0 ][ 2 ];

const s1 = update( s, {
    0: { 1: { $set: v2 } },
    0: { 2: { $set: v1 } }
} );

console.log(s1); //[ [ 1, 2, 2, 4 ] ]
```

Swapping between two different arrays works perfectly fine
```
const s = [ [ 1, 2, 3, 4 ], [ 5, 6, 7, 8 ] ]

const v1= s[ 0 ][ 1 ];
const v2 = s[ 1 ][ 2 ];

const s1 = update( s, {
    0: { 1: { $set: v2 } },
    1: { 2: { $set: v1 } }
} );

console.log(s1); //[ [ 1, 7, 3, 4 ], [ 5, 6, 2, 8 ] ]
```

I am not sure if this is an issue or something wrong with my code.

**Comment by kolodny** [comment]
I didn't catch the bug right away. In your first example you did something like this:

```js
var obj = {
  a: 1,
  a: 2
}
```

Which only keeps the second one. You can rewrite it as follows:

```js
const s1 = update( s, {
    0: {
        1: { $set: v2 },
        2: { $set: v1 }
    },
} );
```
