### ISSUE TITLE
getting error on merge

### ISSUE THREAD

**Issue by jaredmharris** [kolodny/immutability-helper#21]
Error:

Uncaught (in promise) Error: update(): $merge expects a target of type 'object'; got undefined
    at invariant (invariant.js:44)
    at update (update.js:70)
    at update (update.js:104)

line throwing error:
return update( state, {item: {$merge: {[action.key]: action.value}}});

any idea why this is happening? I checked typeof for each and they are both objects.

**Comment by kolodny** [comment]
Can you provide an example of when this happens?

**Comment by goddardcm** [comment]
Just ran into this myself when `originalValue` is undefined. I'm wondering if `$merge` should be made more permissive in that case (it would help me avoid having to test the current state and have to decide whether to do a `$set` or a `$merge`.

Starting state:
```
{
  itemsBySecondaryKeyAndId: {},
}
```

Code:
```js
/* 
  Presume action looks like 
  {
    secondaryKey: '15',
    items: [ {id: 1, name: 'One'}, {id: 2, name: 'Two'} ],
  }
*/

update(state, {
  itemsBySecondaryKeyAndId: {
    [action.secondaryKey]: { $merge: _.keyBy(action.items, 'id') },
  },
});
```

Desired state after update:
```
{
  itemsBySecondaryKeyAndId: {
    15: {
      1: {id: 1, name: 'One'},
      2: {id: 2, name: 'Two'},
    },
  },
}
```

And then if a similar update were called again:
```js
/* 
  Presume action looks like 
  {
    secondaryKey: '15',
    items: [ {id: 3, name: 'Three'}],
  }
*/

update(state, {
  itemsBySecondaryKeyAndId: {
    [action.secondaryKey]: { $merge: _.keyBy(action.items, 'id') },
  },
});
```

I would expect final state to be:
```
{
  itemsBySecondaryKeyAndId: {
    15: {
      1: {id: 1, name: 'One'},
      2: {id: 2, name: 'Two'},
      3: {id: 3, name: 'Three'},
    },
  },
}
```

**Comment by hoytech** [comment]
I believe making $merge more permissive as @goddardcm suggests is akin to implementing [autovivification](https://en.wikipedia.org/wiki/Autovivification), which this module does not implement (see https://github.com/kolodny/immutability-helper/issues/16#issuecomment-289326983).

However, I have created a version of update that does implement autovivification: [update-immutable](https://www.npmjs.com/package/update-immutable).

I also added a test based on this example to demonstrate how this works with $merge:

https://github.com/hoytech/update-immutable/blob/v1.1.0/t/basic.js#L207

Hope this helps.

**Comment by kolodny** [comment]
@goddardcm This currently works at the moment:

```js
var state = {
  itemsBySecondaryKeyAndId: {},
}

var spec = {
  itemsBySecondaryKeyAndId: {
    15: {
      $merge: {
        1: {id: 1, name: 'One'},
        2: {id: 2, name: 'Two'},
      }
    },
  },
};

try {
  var state2 = update(state, spec);
} catch (e) {
  console.log('state.itemsBySecondaryKeyAndId[15] is undefined')
}

state.itemsBySecondaryKeyAndId[15] = {}
var state3 = update(state, spec);

var state4 = update(state3, {
  itemsBySecondaryKeyAndId: {
    15: {
      $merge: {
        3: {id: 3, name: 'Three'},
      },
    },
  },
});

console.log(JSON.stringify(state4, 0, 2));
/* outputs:
{
  "itemsBySecondaryKeyAndId": {
    "15": {
      "1": {
        "id": 1,
        "name": "One"
      },
      "2": {
        "id": 2,
        "name": "Two"
      },
      "3": {
        "id": 3,
        "name": "Three"
      }
    }
  }
}
*/
```

**Comment by goddardcm** [comment]
@kolodny `state.itemsBySecondaryKeyAndId[15] = {}` mutates `state`, which defeats the purpose.

**Comment by kolodny** [comment]
Yeah, I was highlighting the fact that you can't do a deep merge on an undefined object. [You can use the technique outlined here though instead](https://github.com/kolodny/immutability-helper#autovivification)

**Comment by goddardcm** [comment]
Gotcha - thanks!
