### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by ghost** [kolodny/immutability-helper#22]
It would be great to add an explicit license statement to this project to clarify terms of its usage.

This project became an officially recommended replacement for [`react-addon-update`](https://facebook.github.io/react/docs/update.html) which has been deprecated. However in order to use this project, one must be sure about its terms of usage.

**Comment by nilsceberg** [comment]
The [package.json](https://github.com/kolodny/immutability-helper/blob/master/package.json) specifies the license as MIT, but I agree, at least mentioning it in the readme would be great.

**Comment by ghost** [comment]
As far as I saw in the [The MIT License](https://opensource.org/licenses/MIT), it requires the full license text to be included at least as an README:

> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

**Comment by kolodny** [comment]
Done @aae740a

I'll push a new release with those changes soon

**Comment by ghost** [comment]
@kolodny thanks!
