### ISSUE TITLE
push into array when key is not define

### ISSUE THREAD

**Issue by kartikag01** [kolodny/immutability-helper#28]
```
let a = {};
let b = update(a, {c: {$push: [4, 5, 6]}});
console.log("b => ", b); // expected output => b =>  { c: [ 4, 5, 6 ] }
```
but error : update(): expected target of $push to be an array; got undefined.
What should i do insert new field into ```a``` when it doesn't exist

**Comment by kolodny** [comment]
The properties to traverse need to be there in order to set a value nested in an object. See https://github.com/kolodny/immutability-helper/issues/16#issuecomment-289326983

**Comment by hoytech** [comment]
You are looking for a module that supports [autovivification](https://en.wikipedia.org/wiki/Autovivification). I have created a mostly-compatible module called [update-immutable](https://www.npmjs.com/package/update-immutable) which implements this feature:

<pre>
> update({}, { arr: { $push: [1,2,3] } })
{ arr: [ 1, 2, 3 ] }
> update({ arr: [4, 5, 6] }, { arr: { $push: [1,2,3] } })
{ arr: [ 4, 5, 6, 1, 2, 3 ] }
</pre>

**Comment by emanuelherrmann** [comment]
what about just using apply and handle the non existing key in the function?

**Comment by hoytech** [comment]
@emanuelherrmann - Using $apply is more verbose: It requires more code to write, read, debug, and test. Also, if you are transferring updates between clients and servers, $apply will not work since functions cannot be serialized. See #45 for some more discussion.
