### ISSUE TITLE
Changing a file objects name in React.js state

### ISSUE THREAD

**Issue by hellofantastic** [kolodny/immutability-helper#29]
Good Day!
Using React and react-dropzone.

Users can drop files in , a list appears with file names in input boxes so they can change filenames if needed. 
The filelist is set to setState({files: acceptedFiles })
I have the inputs onchange wired to an onchange function.

I quickly found error of read-only for name on `#<File>` object and came across advice to use update from immutability helpers.

So I came up with this 
```javascript
let id = event.target.id; 
this.setState(update(this.state.files[id], {name: {$set: event.target.value }}));  
```
However upon editing the file name in the input that now produces
Uncaught TypeError: Failed to construct 'File': 2 arguments required, but only 0 present.

I get what that means just have no idea how to modify the update() to satisfy the File recreation.

Is this a good place to ask or move over to Stackoverflow?

Thank you if anyone can chime in.

**Comment by SnareHanger** [comment]
I believe your real problem here is that you can't change the name on a File object in JS.

**Comment by hellofantastic** [comment]
haha ahhh! as in thats a set in stone thing?

**Comment by hellofantastic** [comment]
And it would then make sense to keep a separate array that matched up with file object ids and reference it when writing the files.

**Comment by SnareHanger** [comment]
var newFile = new File(["file contents"], "filename.txt");
newFile.name = "newFilename.txt";

console.log(newFile.name); // --> "filename.txt"

Yeah...it's set once the file is created.  I'm assuming this is for security reasons.

**Comment by hellofantastic** [comment]
Thanks
