### ISSUE TITLE
[FEATURE-REQUEST] Add $keyExists command

### ISSUE THREAD

**Issue by trungtin** [kolodny/immutability-helper#32]
I found myself do a lot of this
```
const updateDef = {
  [someKey]: {$push: newArray}
}

if (!state[someKey]) {
  updateDef[someKey]: {$set: newArray}
}

update(state, updateDef)
```

Could we add another command like $keyExists and it work like this:
```
const updateDef = {
  [someKey]: {$keyExists: [ {$push: newArray}, {$set: newArray} ]}
}
```
Happy to make a pull request if you guy found this feature would be helpful

**Comment by hoytech** [comment]
I also can't stand checking if a key exists and then having separate code paths for either case.

Although not capable of everything a potential `$keyExists` command, your use case is solved by [autovivification](https://en.wikipedia.org/wiki/Autovivification). This module does not implement that (see https://github.com/kolodny/immutability-helper/issues/16#issuecomment-289326983).

However, I have a module called [update-immutable](https://www.npmjs.com/package/update-immutable) which does implement autovivification. For example, your use case of creating an array if not already there:

<pre>
> update({}, { arr: { $push: [1,2,3] } })
{ arr: [ 1, 2, 3 ] }
> update({ arr: [1, 2, 3] }, { arr: { $push: [4, 5, 6] } })
{ arr: [ 1, 2, 3, 4, 5, 6 ] }
</pre>

**Comment by kolodny** [comment]
It's possible to accomplish what you are looking for with an even more powerful control of how the object should behave on undefined:

```js
var newArray = ['x', 'y', 'z']
var someKey = 'key'

var updateDef = {
  [someKey]: {$apply: x => update(x || [], {$push: newArray})}
};


var state = {}
var state2 = update(state, updateDef)
var state3 = update(state2, updateDef)

console.log(JSON.stringify({ state, state2, state3 }, 0, 2))
/* outputs:
{
  "state": {},
  "state2": {
    "key": [ "x", "y", "z" ]
  },
  "state3": {
    "key": [ "x", "y", "z", "x", "y", "z" ]
  }
}
*/
```

Let me know if that solves your issue.

**Comment by kolodny** [comment]
I've added a section in the README regarding this: https://github.com/kolodny/immutability-helper#autovivification
