### ISSUE TITLE
It seems `$merge` doesn't really work.

### ISSUE THREAD

**Issue by lnshi** [kolodny/immutability-helper#33]
Like title described, consider about this case:

```
const state = {
  a: 1,
  b: {
    c: 2
  }
}

const tmp = {
  b: {
    d: 3
  }
}

update(state, {
  $merge: tmp
})
```
Gave the result:
```
 {
  a: 1,
  b: {
    d: 2
  }
}
```
Which we lost the original property `c: 2`.

**Comment by hoytech** [comment]
`$merge` is a shallow merge, not a deep merge.

Your case can be solved by (shallow) merging the `b` key instead of the root:

<pre>
> update({ a:1, b:{c:2} }, { b: { $merge: { d: 3 } }})
{ a: 1, b: { c: 2, d: 3 } }
</pre>

**Comment by lnshi** [comment]
@hoytech ok, in this way it works, but how about if I want to `$merge` more deeper? like
```
{
  a: 0,
  b: {
    c: 1,
    d: {
      e: 2
    }
  }
}
// with
{
  b: {
    d: {
      f: 3
    }
  }
}
```

**Comment by hoytech** [comment]
There are multiple ways to deep merge a structure so it depends on what exactly you want to accomplish.

I have added a simple example to the docs for [update-immutable](https://www.npmjs.com/package/update-immutable) (search for deepmerge).

**Comment by kolodny** [comment]
Closing since as @hoytech explained `$merge` only works shallowly
