### ISSUE TITLE
$splice works sequentially

### ISSUE THREAD

**Issue by CAYdenberg** [kolodny/immutability-helper#37]
I'm not sure this is formally a bug but it definitely deviates from expectations from my standpoint.

```js
const res = update([1,2,3,4], {$splice: [[0,1],[1,1]]})
// res = [2, 4]
```

Since the spec for $splice is an array of arrays, I think the targeted indices should not change during the operation. I can't think of many use cases where you could safely use $splice and know ahead of time all the indices of the elements you intend to remove.

**Comment by kolodny** [comment]
See #12 
The gist of why this is left as is, is that splice is capable of completely rewriting the array the first time around, so there is no concept of index state. Consider this

```js
const state = [1,2,3,4]
const state2 = update(state, {
  $splice: [ [0, 0, 'x', 'y', 'z'], [1, 1], [2, 1] ]
})
```

I would have no idea what should happen if we assume that the indices in the array don't change (BTW the current value of `state2` is `['x', 'z', 2, 3, 4]`)

**Comment by CAYdenberg** [comment]
OK, makes sense. Would you accept a PR to fill out the documentation a little bit?

**Comment by kolodny** [comment]
Sure!

**Comment by mnpenner** [comment]
I still think sorting the keys descending first makes sense. In the event that your splices overlap, the result will still be deterministic even if it's non-sense. In the event that they don't, this really helps unexpected behaviour.
