### ISSUE TITLE
a new api to update an object

### ISSUE THREAD

**Issue by agupta93** [kolodny/immutability-helper#38]
we can basically expose another API which takes in an array and the action somewhat like this 

`update (object, pathArray/path, method, value)`

and then do the same thing like the current API does

**Comment by alanwei0** [comment]
@agupta93 i have written a lib to support the api you want, and i will publish it to github this week.

**Comment by nekronhuang** [comment]
@agupta93 
You can use lodash to help you. For example:
```js
const expr = _.set({}, 'a.b.c', { $set: 1 })
// then expr will be { a: { b: { c: { $set: 1 } } } }
update(object, expr)
```
Howerver, if you want update an array, you should use like this:
```js
const exprt = _.setWith({}, 'a.0', { $set: 1 }, Object)
// expr will be { a: { 0: { $set: 1 } } }
```

Of course, you can wait for the library from @alanwei0 .

**Comment by alanwei0** [comment]
@agupta93 https://github.com/ProtoTeam/immutability-helper-x

**Comment by hoytech** [comment]
I have implemented a very similar feature in update-immutable. You can read the documentation and see a few examples here:

https://www.npmjs.com/package/update-immutable#updatepath
