### ISSUE TITLE
Autovivification documentation is misleading

### ISSUE THREAD

**Issue by hoytech** [kolodny/immutability-helper#45]
Thanks for documenting autovivification in your README. This will provide a response to the many people who run into this, as you've no doubt noticed by the number of github tickets related to this (on the react as well as your bugtracker). A few points though:

1) The fundamental reason why autovivifying arrays in JS is difficult is that the same `[]` operator is used for both array and object access so there is no way to disambiguate which one an autovivification is intended to create. However, `update` is not implementing JS, but instead its own mini-language. There's no reason that we can't decide "path" autovivification is only supported for objects, which in my experience is what is needed in the vast majority of instances (note that all tickets on the react and your bugtrackers are suggesting object autovivification only).

2) Even in the cases where you wish to autovivify an array, `$push`, `$splice`, and `$unshift` can be used to create arrays with no ambiguity (at the leaf level only). Again, anecdotally, `$push` seems to be a much more common way of adding to an existing array than `$set`. Since it's obvious `$push` and company intend to operate on arrays, there is no problem autovivifying in these cases.

3) Your suggested example using `$apply` has three issues from my perspective:
    * `$apply` updates cannot be transferred between client and server since functions cannot be serialised
    * Each `$apply` has two code paths (the default `[]`/`{}` path and the path for when the target already exists) and therefore ought to be tested in both scenarios
    * Although subjective, to me this method seems more complicated and difficult to maintain

4) Adding autovification to `update` is not "practically impossible". In fact, I have implemented it in my version: [update-immutable](https://www.npmjs.com/package/update-immutable). If you choose to not implement autovivification in your module (a decision I sympathise but do not agree with) then can you at least please link to a "dissenting opinion" on this topic?

Regards,

Doug

**Comment by schtauffen** [comment]
Additionally,

You could easily check whether the variable in the bracket is a number or not. 
Objects always have string keys, Arrays always have number indexes. 

```js
var state = {}
state.thing[0] = 'foo' // state = { thing: ['foo'] }
state.thing2[1] = 'foo2' // state = { thing: ['foo'], thing2: [undefined, 'foo2'] }
state.thing3 = ['thing3'] // state = { thing: ['foo'], thing2: [undefined, 'foo2'], thing3: ['thing3'] }
state.thing3[1] = 'foo3' // state = { thing: ['foo'], thing2: [undefined, 'foo2'], thing3: ['thing3', 'foo3'] }
state.thing2.slice // should be defined by prototype
state.thing2.slice // should be a function
```
This proves even when you do a "number" key for an object, it is simply being coerced into a string:
```js
const a = {}
a[0] = 1
Object.keys(a) // ["0"]
```

**Comment by hoytech** [comment]
@schtauffen - This is a good point. In a different form of the update language, `typeof` could be used to differentiate between array indices and object keys. Unfortunately, the current update language always stores update paths as nested objects which, as you mentioned, will coerce the indices into strings, losing the fact that they may have originally been numbers.

Personally I've never needed to autovivify an array (except with push/unshift of course) so I've never attempted to solve this issue.

**Comment by kolodny** [comment]
I've come up with an escape hatch to cover your use cases. Let me know if you have any objections, if not, I'll look into adding it to the docs in the autovivification section

```js
update.extend('$auto', function(value, object) {
  return object ?
    update(object, value):
    update({}, value);
});
update.extend('$autoArray', function(value, object) {
  return object ?
    update(object, value):
    update([], value);
});

var state = {}
var state2 = update(state, {
  foo: {$autoArray: [
    {$auto: {
      bar: {$autoArray: {$push: ['w', 'x', 'y']}}
    }}
  ]}
});
var state3 = update(state2, {
  foo: {$autoArray: [
    {$auto: {
      bar: {$autoArray: {$push: ['z']}}
    }}
  ]}
});
console.log(JSON.stringify({ state2, state3 }, 0, 2))

/* Outputs:
{
  "state2": {
    "foo": [
      {
        "bar": [
          "w",
          "x",
          "y"
        ]
      }
    ]
  },
  "state3": {
    "foo": [
      {
        "bar": [
          "w",
          "x",
          "y",
          "z"
        ]
      }
    ]
  }
}

*/
```

**Comment by hoytech** [comment]
Interesting approach. In my opinion it's much better than the nested updates suggested previously.

I personally prefer using the same syntax as normal updates and to not add those `extend` lines in every project, but this is of course implemented in [update-immutable](https://www.npmjs.com/package/update-immutable) which I have entirely switched to so I have no complaints. My main objection was just the claim that it was practically impossible, which you have just demonstrated wasn't accurate. :)

So ya, looks like a reasonable solution. Thanks!

**Comment by mikeplis** [comment]
+1 for supporting object-only autovivification. I think that's a reasonable default and would cover a lot of use cases.

I'd be happy to attempt a PR if it'll be considered, though you're well within your rights to not want this feature in the repo. The `$auto` extension you mentioned above looks like it would work just fine. I just wanted to add my voice to the discussion.

**Comment by kolodny** [comment]
Updated docs in `2.3.0`

**Comment by xavibonell** [comment]
I just run into this issue, at first I couldn't believe autovivification was not implemented by default. I switched to @hoytech solution, works out of the box. You should really consider implement that solution on your repo, not just in your README, is a must have. Thanks both anyway for making everyone else's life easier!
