### ISSUE TITLE
Unable to resolve module 'immutability-helper'

### ISSUE THREAD

**Issue by Symous** [kolodny/immutability-helper#46]
Hi , I am using React Native 0.43 with Android Platfrom.
Even I have import update from 'immutability-helper' it still give me an error that - 
Unable to resolve module 'immutability-helper' rom [MY_DIRECTORY];Modules does not exist in the module map or in theres directories ....

**Comment by kolodny** [comment]
Can you give me a minimal way to repro this bug?
