### ISSUE TITLE
Support for symbols missing?

### ISSUE THREAD

**Issue by salujaharkirat** [kolodny/immutability-helper#48]
I was trying to use `update` with `apollo-client`. I see support for symbols was added in 2.1.0 but its still not working for me.

**Original data**:
Object {goal: Object, Symbol(id): "ROOT_QUERY"}

**Update code**

```
          const updatedData = update(data,{
            "goal": {
              "baseSips": {"$apply":baseSips => {
                if (baseSips) {
                  return update(baseSips[0],{"$set":[baseSip]});
                }
                return update([],{"$push":[baseSip]});
              }}
            }
          }
        );
```

**Updated data**
Object {goal: Object}

I am trying on version **2.2.0**

**Comment by kolodny** [comment]
Can you give me a more through example. How would I reconstruct `data` and what's `baseSips`?

**Comment by kolodny** [comment]
Closing for now, feel free to reopen if you can repro
