### ISSUE TITLE
Exception TypeError: object.constructor is not a constructor

### ISSUE THREAD

**Issue by Kyr** [kolodny/immutability-helper#49]
This exception caught at https://github.com/kolodny/immutability-helper/blob/master/index.js#L24 in case I'm try to update object created via `Object.create(null)`.
It's could be resolved with replacement 
`return assign(new object.constructor(), object);` to `return assign(Object.create(object.prototype || null), object)`

**Comment by kolodny** [comment]
Thanks for the report. A fix for this has been [pushed and published](https://github.com/kolodny/immutability-helper/compare/41b5b60e06905d0947384add1c08940c7568ba3f...cee08c9768a6e7608e7fb5a88469827c548353b8). Please try it out and let me know if your issue is resolved. Thanks!
