### ISSUE TITLE
import statement in readme seems to be wrong

### ISSUE THREAD

**Issue by seansfkelley** [kolodny/immutability-helper#5]
The docs have this snippet:

``` js
// import update from 'react-addons-update';
import update from 'immutability-helper';
```

But the export looks like this:

``` js
module.exports = newContext();
```

Which works when you follow the [docs on `react-addons-update`](https://facebook.github.io/react/docs/update.html) (seeing as it's a drop-in replacement) for the import:

``` js
// var update = require('react-addons-update');
var update = require('immutability-helper');
```

But it doesn't work when you use a bundler to transpile from ES6, because the docs' ES6-style default import is misleading (this particular one is from my Webpack project):

``` js
Uncaught TypeError: immutability_helper_1.default is not a function
```

So should the interface be changed or the docs updated? I'm guessing the latter.

**Comment by kolodny** [comment]
I can't seem to replicate. [Playing around in the babel repl it looks like it should work too](http://babeljs.io/repl/#?evaluate=true&presets=es2015&experimental=false&loose=false&spec=false&code=import%20update%20from%20'immutability-helper'%3B%0D%0A%0D%0Aconsole.log%28update%29%3B), what does your `.babelrc` file looks like?

**Comment by seansfkelley** [comment]
Ah, looks like Babel tries to be clever and will see if it's compiled by other Babel by looking for `__esModule`. I'm actually consuming this from Typescript, [which doesn't try to be clever](https://www.typescriptlang.org/play/#src=import%20update1%20from%20'immutability-helper'%3B%0D%0A%0D%0Aimport%20*%20as%20update2%20from%20'immutability-helper'%3B%0D%0A%0D%0Aimport%20update3%20%3D%20require%28'immutability-helper'%29%3B%0D%0A%0D%0Aconsole.log%28update1%2C%20update2%2C%20update3%29%3B) (ignore the usage of `define` over `require`, it's just doing that cause its in the browser).

Strictly speaking, the way it's defined (namely, `module.exports = ...`) it should not be importable using default-import syntax, but Babel is trying to be helpful. [Typescript explicitly doesn't do this](https://github.com/Microsoft/TypeScript/issues/2719) and [Babel 6 stopped being clever about not emitting `.default` in some scenarios](http://stackoverflow.com/questions/33505992/babel-6-changes-how-it-exports-default), so I think it's probably not behavior that should be depended upon.

**Comment by WaldoJeffers** [comment]
@seansfkelley : I'm having the exact same issue with TypeScript. How did you manage to solve it ? @kolodny shouldn't ImmutabilityHelper be exported with the ES6 syntax (`export default ...`)

**Comment by kolodny** [comment]
There's no es6 in this project. I can make it a little more module friendly by adding  
`module.exports['default'] = module.exports`

**Comment by seansfkelley** [comment]
@waldojeffers for libraries like this, you can always `import * as update from 'immutability-helper'`, though depending on how exactly they are typed it may not actually work. I wrote the things for this library on DT, so I can assure you it works. :)

@kolodny it's still correct in javascript to import without `default`. It's probably still worth changing the docs or adding that export statement you mention.
