### ISSUE TITLE
Bug? Unexpected effect of {$set: undefined} to object

### ISSUE THREAD

**Issue by ericfong** [kolodny/immutability-helper#55]
Testing on version: immutability-helper@2.3.0

Not sure this is a bug or not.

When directly setting undefined to object
```js
const obj = {}
obj.x = undefined
Object.keys(obj) === ['x']
```

set undefined by immutability-helper
```js
const obj2 = immutabilityHelper({}, { x: { $set: undefined } })
Object.keys(obj2) === []  // WITHOUT 'x'
```
I was expecting `undefined` will be set to obj2 and Object.keys(obj2) === ['x']. 

update undefined to object which already have x
```js
const obj3 = immutabilityHelper({ x: 1 }, { x: { $set: undefined } })
Object.keys(obj3) === ['x']  // WITH 'x'
obj3.x === undefined
```

**Comment by kolodny** [comment]
Thanks for this bug report. This is indeed a bug and has been fixed by @georapbox and published in `2.3.1`
