### ISSUE TITLE
Feature request: flow type support

### ISSUE THREAD

**Issue by nlieb** [kolodny/immutability-helper#57]
It would be great to add flow type support for this library, either here or in flow-typed.

**Comment by andreiglingeanu** [comment]
I somehow asked exactly that on [twitter](https://twitter.com/AGlingeanu/status/868130726276976640). @kolodny mentioned that there are some [typescript](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/immutability-helper) typings but they are outdated.

And to be fair, the dynamic nature of the spec objects is very hard to safely typecheck, as far as I'm familiar with what flow can do. Don't know too much about typescript though.

**Comment by garkin** [comment]
[Here is](https://gist.github.com/garkin/db4ad0efd20a75a5ada3726cc783173f) a more strict version of the TypeScript typings than a DefinitelyTyped current one.

**Comment by kolodny** [comment]
This is great, can you make a PR for this?

**Comment by kolodny** [comment]
Is anyone able to pick this up?

**Comment by andreiglingeanu** [comment]
I could try to get over it on the next weekend, if that's okay. If someone is able to get on it earlier -- ping here

**Comment by gnapse** [comment]
I may have time before the weekend, but I wish I had the expertise on typescript to take it, so I leave it to you @andreiglingeanu. Just take into account that as of #72 the `spec` argument to `update` (typed `Query<T>` in the [gist](https://gist.github.com/garkin/db4ad0efd20a75a5ada3726cc783173f) linked to above) can also be a `function`, in addition to possibly being an object or an array. Most surely that gist does not account for that, being this a new feature added today.

**Comment by andreiglingeanu** [comment]
Already implemented for TypeScript. Should be trivial to implement for flow too (and also submit a PR to flow-typed repo).

**Comment by mpyw** [comment]
It's impossible on the current version of  Flow. Flow cannot represent the following statement.

```ts
type Tree<T> = {[K in keyof T]?: Query<T[K]>}
```

**Comment by andreiglingeanu** [comment]
Yes, true. And by the way, TypeScript just [landed](https://blogs.msdn.microsoft.com/typescript/2018/03/15/announcing-typescript-2-8-rc/) conditional types in 2.8 RC, it might be a good opportunity to strengthen TS types using them

**Comment by jednano** [comment]
After [this tweet](https://twitter.com/jamiebuilds/status/1064649666275340288), is Flow even relevant any more?

**Comment by kolodny** [comment]
I'm OK with dropping it, I don't see anyone ever implementing it either way. If someone finds this in the future and is interested, feel free to create a PR
