### ISSUE TITLE
$unshift command produces results different from react-addons-update

### ISSUE THREAD

**Issue by 7fffffff** [kolodny/immutability-helper#6]
```
var update1 = require('react-addons-update'); // 15.3.2
var update2 = require('immutability-helper'); // 2.0.0

var original = [1, 2, 3];
var r = update1(original, {$unshift: [4, 5, 6]});
var i = update2(original, {$unshift: [4, 5, 6]});

console.log(r); // [ 6, 5, 4, 1, 2, 3 ]
console.log(i); // [ 4, 5, 6, 1, 2, 3 ]
```

**Comment by kolodny** [comment]
I'm not sure how I feel about this. I would guess that this is a bug in react-addons-update. Consider the following

``` js
const arr = [1, 2, 3];
arr.unshift(4, 5, 6);
console.log(arr); // [4, 5, 6, 1, 2, 3]
```

Reference: https://github.com/facebook/react/blob/master/src/addons/update.js#L119-L121

**Comment by 7fffffff** [comment]
I don't have an opinion about which way is the right way.

To me, the strongest argument in favor of adopting react-addons-update's behavior is the [deprecation  notice](https://facebook.github.io/react/docs/update.html) that points to immutability-helper, and that the README describes immutability-helper as a drop-in replacement.

At least, the difference should be spelled out to prevent surprise.

**Comment by arolson101** [comment]
I filed a bug in the react-addon-update about this very thing:
https://github.com/facebook/react/issues/5312

**Comment by kolodny** [comment]
I'm going to leave things as is, if anyone comes across this issue, they can duplicate the buggy behavior as follows:

``` js
update.extend('$unshift', function(value, original) {
  return value.slice().reverse().concat(original);
});
```
