### ISSUE TITLE
Updating an updated collection broken in Windows 8.1 IE 11

### ISSUE THREAD

**Issue by clickblipclick** [kolodny/immutability-helper#65]
Hi there,

In IE 11 I am seeing a very strange issue when updating a collection that has already been updated once. Code sample below:

```javascript
import update from "immutability-helper";

var idToUpdate = "4";

const collection = {
  "0": { selected: false },
  "1": { selected: false },
  "2": { selected: false },
  "3": { selected: false },
  "4": { selected: false },
  "5": { selected: false },
  "6": { selected: false }
};

const updatedCollection = update(collection, { [idToUpdate]: { selected: { $set: true } } });
console.log(updatedCollection["3"], updatedCollection[idToUpdate]);
// This logs as expected, setting collection["4"].selected to true in IE 11

const secondUpdatedCollection = update(updatedCollection, { [idToUpdate]: { selected: { $set: false }}});
console.log(secondUpdatedCollection["3"], secondUpdatedCollection[idToUpdate]);
// In the second update, the "secondUpdatedCollection" only has the "4" key, all the rest of the keys are missing
```

This works properly on Edge and all other browsers I've tested, but breaks on IE11 (I am assuming other IE versions as well). It's possible I'm overlooking something totally obvious, but I'm not sure what. Any help would be appreciated!

Thanks.

**Comment by kolodny** [comment]
A couple of things off the bat, that syntax wouldn't work in IE11 at all (`const` isn't supported), also I noticed you're logging just the property to update and not the whole collection. Here's what I tried to replicate with no success (note: I just appended the snippet to the index.js file and index.html just serves that file)

![image](https://user-images.githubusercontent.com/1187604/31868527-e84abd88-b76d-11e7-8326-b3b0f5eb82a1.png)

Am I missing something?

**Comment by clickblipclick** [comment]
Hi there,

Sorry for the confusion, I was using polyfilled/transpiled code.

I've uploaded a repo here: https://github.com/clickblipclick/immutability-example
And the output here: http://immutibility-example.s3-website-us-east-1.amazonaws.com/

I've also done some more testing and this either seems like a problem with the specific install of IE, or a very specific browser version issue, or related to the version of Windows it's running on. This is IE 11 on Windows 8.1 which I am testing on browserstack.com.
<img width="388" alt="screen shot 2017-10-22 at 11 27 54 pm" src="https://user-images.githubusercontent.com/1479810/31871229-ce24691e-b780-11e7-8e62-d595063eebf7.png">

When I try IE 11 on Windows 7 or 10 or IE 10 on Windows 8, it works as expected.

This is the output on Windows 10 IE 11, which gets cut off in the screenshot (but it all prints as expected):
<img width="507" alt="screen shot 2017-10-22 at 11 31 19 pm" src="https://user-images.githubusercontent.com/1479810/31871292-2dd59bee-b781-11e7-9ad2-ea74e5d464a2.png">

This is the output on Windows 8.1 IE 11 (you'll see the second and third logs are just empty brackets):
<img width="446" alt="screen shot 2017-10-22 at 11 31 36 pm" src="https://user-images.githubusercontent.com/1479810/31871301-3355eb00-b781-11e7-8594-ee5ba6e35e96.png">

There are honestly so many things it could be, from polyfill bugs to browser bugs to a bug on this specific machine, I don't expect you to fix but in case it's something simple there's the example.

**Comment by kolodny** [comment]
Weird, it's all there for me. Might be compatibility mode (although, it didn't change anything for me)?  
Either way closing for now

![image](https://user-images.githubusercontent.com/1187604/32029686-2b6f9144-b9c4-11e7-92e6-3ec227366082.png)
