### ISSUE TITLE
$merge do not generate new object

### ISSUE THREAD

**Issue by sigvamo** [kolodny/immutability-helper#66]
Hi,

I updated immutability-helper to the current version and found the next issue. 
I used $merge in previous version to clone my object and then do some modifications on it:

newObj = update(oldObj, {$merge: {} } )

newObj == oldObj was False

But with new version

newObj == oldObj is True

Is it intentionally so or it is not expected, now I should review all the code.

**Comment by kolodny** [comment]
This is intentional, it was done in 9c0134d

If you want to shallow clone and object you can do `newObj = Object.assign({}, oldObj)`

**Comment by sigvamo** [comment]
Thank you for the answer.

Yes I already rewrited the code. It was just surprise, because it worked before.

Thank you.
