### ISSUE TITLE
Trying to update state

### ISSUE THREAD

**Issue by thewebsitedev** [kolodny/immutability-helper#7]
Hello,

I have a simple piece of code as shown below:
```
for (var i = this.state.structure.length - 1; i >= 0; i--) {
    this.state.structure[i].active = false
    if( this.state.structure[i].id == id ){
        this.state.structure[i].active = true
    }
}
this.forceUpdate()
```
This code works fine and the state is updated as required. But when I try to do the same using immutability helper then it does not work. Seems like it runs only for the first time as all values are set to false.
```
for (var i = this.state.structure.length - 1; i >= 0; i--) {
    this.setState({
        structure: update(this.state.structure, {[i]: {active: {$set: false}}})
    })
    if( this.state.structure[i].id == id ){
        this.setState({
            structure: update(this.state.structure, {[i]: {active: {$set: true}}})
        })
    }
}
```
What I am doing wrong here?

**Comment by kolodny** [comment]
I suspect that you're calling the code in a event callback, but either way [`setState` is an async action that takes a callback of when the state is guaranteed to have the desired changes.](https://facebook.github.io/react/docs/react-component.html#setstate)

The simplest way to do what you want is as follows:

``` js
for (var i = this.state.structure.length - 1; i >= 0; i--) {
  var state = this.state;
  state = update(state, {
    structure: {
      [i]: {
        active: {$set: this.state.structure[i].id == id}
      }
    }
  });
  this.setState(state);
}
```

**Comment by thewebsitedev** [comment]
Thank you for the quick response! Yes, I am doing this using event handler.

I just tried the code you provided but result is same as before. All values are set to false.

This is the structure I have:

```
{
    "structure":
    [
        {
            "id":"desktop",
            "name":"Desktop",
            "active":true,
        },
        {
            "id":"tablet",
            "name":"Tablet",
            "active":false,
        },
        {
            "id":"mobile",
            "name":"Mobile",
            "active":false,
        }
    ]
}
```

**Comment by kolodny** [comment]
I wrote that in a hurry. My main mistake was assigning `var state = this.state` inside the loop. `setState` should also be called after the loop completes. This should work:

``` js
var state = this.state;
for (var i = state.structure.length - 1; i >= 0; i--) {
  state = update(state, {
    structure: {
      [i]: {
        active: {$set: this.state.structure[i].id == id}
      }
    }
  });
}
this.setState(state);
```

**Comment by thewebsitedev** [comment]
It works now! Thanks a lot.
