### ISSUE TITLE
$apply syntax shortening

### ISSUE THREAD

**Issue by eugene-beliaev** [kolodny/immutability-helper#70]
Now for a function application we need to use the syntax like that
```js
const mul = a => b => a * b
update(numbers, { one: { $apply: mul(2) }})
```

What do you think about shortening the syntax like that?
```js
update(numbers, { one: mul(2) })
```
Looks more declarative.

**Comment by kolodny** [comment]
That makes senses. It's not like a function can be anything other than a leaf anyway. I'd be open to a PR

**Comment by gnapse** [comment]
This has somewhat big implications. For instance, it cannot be assumed anymore that the update spec is an object. Just by trying to clone the tests of `$apply` to write them for the new proposed notation, I see this

```javascript
update({ v: 2 }, { $apply: applier })
```

which now becomes this

```javascript
update({ v: 2 }, applier)
```

Is that correct?

I'm willing to attempt a PR, if no one else is working on this. Any tips would be appreciated.

**Comment by kolodny** [comment]
Awesome! I would imagine you'd put something similar to [`commands` lookup check](https://github.com/kolodny/immutability-helper/blob/0db15587bd60777a5f109420033be32ca0a2e6a4/index.js#L70) and also check if the objects `typeof` is `function`

Thanks
