### ISSUE TITLE
Consider alternative to address deeply nested paths

### ISSUE THREAD

**Issue by gnapse** [kolodny/immutability-helper#71]
Consider the following real-life example:

```javascript
return update(state, {
  objects: {
    [resource]: {
      [id]: {
        relationships: {
          [action.relationship]: {
            data: {
              $apply: data => {
                const { id, type } = response.data;
                const ref = { id, type };
                return data == null ? [ref] : [...data, ref];
              }
            }
          }
        }
      }
    }
  }
});
```

I wish there was a shortcut for addressing something that deeply nested, without all the actual nesting, extra indentation and all the ceremony. I'm not sure exactly how this could be solved. My first idea was something around this pseudo-code:

```javascript
return update(state, {
  something: { // <- some way to encode the path in here, without it being conflated with an actual key
    $apply: data => {
      const { id, type } = response.data;
      const ref = { id, type };
      return data == null ? [ref] : [...data, ref];
    }
  }
});
```

However, I'm not sure what that "something" could be that doesn't get mistaken with an actual object attribute key.

My second attempt is maybe less obvious at first, but more doable from a syntactic point of view:

```javascript
return update(state, {
  $path: `objects.${resource}.${id}.relationships.${action.relationship}.data`,
  $apply: data => {
    const { id, type } = response.data;
    const ref = { id, type };
    return data == null ? [ref] : [...data, ref];
  }
});
```

This special `$path` key could be used anywhere where any other operation key is usable, and indicates that the modification is not meant to be applied at this point in the state tree, but instead following the given path from this point downwards, and to wherever it leads, apply the modification there.

Makes sense? Or maybe there are other ways to approach this? Or maybe the problem I think I'm facing is not considered a problem?

**Comment by kolodny** [comment]
This has come up before. A great tool to turn something like `objects.${resource}.${id}.relationships.${action.relationship}.data` into an object is the [flatulence](https://github.com/mephju/flatulence) library. See https://github.com/kolodny/immutability-helper/issues/64#issuecomment-344334937

In your case that would turn into:

```js
return update(state, flatulence.unflatten({
  "objects.${resource}.${id}.relationships.${action.relationship}.data.$apply": data => {
    const { id, type } = response.data;
    const ref = { id, type };
    return data == null ? [ref] : [...data, ref];
  }
});
```

**Comment by wongjiahau** [comment]
Maybe you can consider my library https://github.com/wongjiahau/modify-via-query
