### ISSUE TITLE
Right way to rename key of object

### ISSUE THREAD

**Issue by danziamo** [kolodny/immutability-helper#73]
Hello.

For example i have an obj, need to rename key `t.a` to `t.b`
```js
const original = {
    t: { 
      a: [1, 2, 3],
      d: { m : 5 }
    }
};
//update.extend('$magicRenaming, function(....))
const final = {
    t: { 
       b: [1, 2, 3],
       d: { m: 5 }
    }
};
assert.equal(original.t.a, final.t.b)
```
I know it might be possible to first unset 'a', than set it again with 'b', but,
What is a good way renaming key 'a' to key 'b'  using immutability-helper?
Keeping an order in object would be nice also

Thank you.

**Comment by kolodny** [comment]
There's a new shorthand `$apply` notation.
If you're using Object rest/spread you can do something like this:

```js
var original = {
    t: { 
      a: [1, 2, 3],
      d: { m : 5 }
    }
};
updated = update(original, {
  t: obj => {
    const {a, ...rest} = obj;
    return {...rest, b: a}
  }
});
assert(original.t.a === updated.t.b)
```

Without spread you can do something like:

```js
updated = update(original, {
  t: obj => {
    const ret = Object.assign({}, obj);
    ret.b = ret.a
    delete ret.a
    return ret
  }
});
assert(original.t.a === updated.t.b)
```

If you really wanted to preserve order you can do those steps in a `for in` or in `Object.keys()`
