### ISSUE TITLE
how to use immutability-helper remove elements from array 

### ISSUE THREAD

**Issue by est7** [kolodny/immutability-helper#78]
```var update = require("immutability-helper")
var state = [{name:'a'},{name:'b'},{name:'c'},{name:'d'}];
var indexToRemove = state.findIndex(item => item.name === 'c');
var newState = update(state, {$splice: [[indexToRemove, 1]]});
console.log(newState); // [{name: "a"}, {name: "b"}, {name: "d"}]```


if i have a list  var list=['a','c'],
how to remove two elements from array 'state'

**Comment by gnapse** [comment]
@es7 this is more a question for StackOverflow than an issue with this library. Please prefer to ask questions there instead of here.

Short answer: what you pass to `$splice` is an array with the parameters that you would pass to javascript arrays' [`splice`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/splice) function. Check out that function's documentation and you'll know how to use `$splice`.

**Comment by joelcollinsdc** [comment]
I also think its very confusing that there is no similar method to push for removing elements

**Comment by gnapse** [comment]
@joelcollinsdc my first instinct when reading your message was that perhaps it makes sense, and I was almost starting to make a PR to propose the new command, when I realized is not that simple.

`$push` is a lot simpler, it always works by appending items at the end of the array. A potential `$delete` action would raise some questions: would it let remove by index? Or by value? If it's by value, would it remove all occurrences of that value in the array? I'm not saying it can't be done, I'm just saying there's no way to satisfy every different need, there are a few different ways in which to approach removing items from an array.

Perhaps the simplest approach, without bloating the set of commands this library provide, is to use the `$apply` command to provide a function that specifically address what's needed in each case, describing the state transformation one wants to achieve. And it becomes even simpler with [the new shorthand notation for `$apply`](https://github.com/kolodny/immutability-helper#shorthand-apply-syntax). The `$splice` command is still useful in some cases of deletion as well:

```javascript
// Delete a value (7) if found, all occurrences
update(state, {
  items: arr => arr.filter(item => item != 7),
})

// Delete a value (7) if found, first occurrence only
const index = state.items.indexOf(7);
if (index >= 0) {
  update(state, { items: { $splice: [[index, 1]] } });
}

// Delete at a specific index, no matter what value is in it
update(state, { items: { $splice: [[index, 1]] } });
```

As you see none of these are that complex to merit its own command, and they're all valid criteria for deleting, depending on the situation at hand. These differences make a generic `$delete` command difficult to incorporate.

Finally, if you really need this command, in the form of one of the cases described above, several times in your app, you can always [declare custom commands](https://github.com/kolodny/immutability-helper#adding-your-own-commands).

**Comment by joelcollinsdc** [comment]
Thanks @gnapse, I really appreciate the explanation.  I'm a bit new to more modern JS so I found myself trying each function that sound remove-y (unset, etc) before realizing that I was barking up the wrong tree.  For what its worth I ended up using $apply with Ramda's helper functions (http://ramdajs.com/docs/#without)

**Comment by kolodny** [comment]
Closing this for now, feel free to reopen if you have any more followup questions

**Comment by charlax** [comment]
Would you consider adding this to the list of examples?

**Comment by GaddMaster** [comment]
Would be nice to see any giant list of all sorts of examples. I'm always struggling with the library. Is there one
