### ISSUE TITLE
"typings" set in package.json, but no typings included

### ISSUE THREAD

**Issue by ghost** [kolodny/immutability-helper#79]
`package.json` includes `"typings": "index.d.ts",`, but there is no `index.d.ts` file.
This was found as part of an automated search of DefinitelyTyped `@types/foo` packages where `foo` is already bundled with types. If you do want to bundle them, that's great, and we can remove [them](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/immutability-helper/index.d.ts) from DefinitelyTyped.

**Comment by andreiglingeanu** [comment]
Hey @andy-ms, they were indeed published but very quickly it got dropped out because of #76. There is actually a pending PR (#77) to get them back. 

BTW, would love some feedback on the quality of typings :)
