### ISSUE TITLE
References not always preserved?

### ISSUE THREAD

**Issue by kachkaev** [kolodny/immutability-helper#8]
Here's an example of a potentially incorrect behaviour:

```js
const orig = {
  a: [1, 2],
  b: [3, 4],
  c: [5, 6],
}

const result = update(orig, {
  $set: {
    b: [7, 8],
  }
});

console.log(
  orig.a === result.a,
  orig.b === result.b,
  orig.c === result.c,
);
```

Expected: ` true, false, true`, got `false, false, false`.

I'd expect the above example to give the same result as the native spread operator:

```js
const orig = {
  a: [1, 2],
  b: [3, 4],
  c: [5, 6],
}

const result = {
  ...orig,
  b: [7, 8],
};

console.log(
  orig.a === result.a,
  orig.b === result.b,
  orig.c === result.c,
);
```
This gives ` true, false, true`, as expected.

The issue may be related to #1.

**Comment by kolodny** [comment]
You seem to be calling the api incorrectly. It should be

```js
const result = update(orig, {
  b: { $set: [7, 8] }
});
```


Try pasting this into [requirebin](http://requirebin.com/)

```js
var update = require('immutability-helper')

const orig = {
  a: [1, 2],
  b: [3, 4],
  c: [5, 6],
}

const result = update(orig, {
  b: { $set: [7, 8] }
});

document.body.innerHTML = '<pre>' + [orig.a === result.a, orig.b === result.b, orig.c === result.c].join(' ')
```

I get this

![image](https://cloud.githubusercontent.com/assets/1187604/20541268/7e21c94c-b0ca-11e6-8087-522268841ded.png)

**Comment by kachkaev** [comment]
Ah, OK. Thanks a lot for taking time to clarify this! Looks like I got confused by some MongoDB experience :–)

**Comment by kolodny** [comment]
:D

For the record what you're doing is valid, it's just setting the root of
the object to `{b:[7,8]}`
