### ISSUE TITLE
immutability-helper should update typescript def

### ISSUE THREAD

**Issue by slashhuang** [kolodny/immutability-helper#82]
## 【emergency】New index.d.ts needed for generic type issue using typescript 2.6.2.

we are a heavy user of immutability-helper using typescript, really awesome npm module.

Hope you can publish new index.d.ts for generic type issue for compatibility issue in new typescript version.

many thanks

**Comment by kolodny** [comment]
V2.6.3 had ts bindings, did you try using that version?

**Comment by kolodny** [comment]
Sorry the #81 was merged and released as `v2.6.4`, try that version

**Comment by kolodny** [comment]
Closing for now, fell free to reopen with any followup questions
