### ISSUE TITLE
Shorthand $set syntax

### ISSUE THREAD

**Issue by jpkleemans** [kolodny/immutability-helper#88]
Now that we have the `$apply` shorthand for `functions`, wouldn't it be logical to automatically treat all other [primitive](https://developer.mozilla.org/en-US/docs/Glossary/Primitive) values as `$set` commands? I think `$set` is the most used command, so that would be very convenient.

Like this:
```js
update({a: 1}, {a: 2})
```
Would be the equivalent of:
```js
update({a: 1}, {a: {$set: 2}})
```

**Comment by kolodny** [comment]
I'm not 100% on board with that. Having a very noticeable directives object with a weird `$set` syntax makes it easy to reason about what's happening. Having a shorthand for `$apply` doesn't really take away that intuition. I'm curious as to what others feel about this.

**Comment by andreiglingeanu** [comment]
I feel like here the explicitness is better than implicitness. It's too easy to put a primitive value in place & get a `$set` that is not desired. When you write a function as a shorthand for `$apply`, on the other hand, you really mean it and it can't be done easily by mistake.

**Comment by kolodny** [comment]
I'm going to close this for now. If more people feel strongly about this we can revisit
