### ISSUE TITLE
Change object at key in a Map?

### ISSUE THREAD

**Issue by xinitrc86** [kolodny/immutability-helper#89]
I'm having a strange behavior with the following code

```
const someState= {
                accounts: new Map([
                    ['102030',{                      
                        name: 'Main',
                        amount: 10
                    }]
                ])
            }
```
And then, inside a reducer:
```
const newState =  update(someState,{
        accounts: 
            {[action.hash]:   
                {$set: {name: 'teste'} }}})
console.log(newState)
console.log src\accounts\tests\reducer.test.js:110
    Map {
      '102030' => { name: 'Main', amount: 10 },
      '102030': { name: 'teste' } }
```
Is this expected? Or am I doing something wrong? Thank you!

**Comment by kolodny** [comment]
The issue with what you're doing is that you're trying to access an element in a Map by using the object notation. Javascript objects (not Maps) use strings as keys and anything else used is converted to a key. Consider the following:

```js
const a = {};
const b = {};
const hash = {
  [a]: 1,
  [b]: 2,
};
Object.keys(hash); // ["[object Object]"]
```

The only feasible way to accomplish what you want at the moment is:

```js
const hash = '102030'
const someState = {
  accounts: new Map([
    [hash, {
      name: 'Main',
      amount: 10
    }]
  ])
}

const newState = update(someState, {
  accounts: accounts => {
    const newSet = new Map(accounts);
    newSet.set(hash, update(newSet.get(hash), {name: {$set: 'teste'}}));
    return newSet;
  }
})
console.log(newState); // { accounts: Map { '102030' => { name: 'teste', amount: 10 } } }

```

This is bad. We should be handling this. I'm going to leave this issue open until we deal with this. Thanks for the report!

**Comment by jinixx** [comment]
Am I doing anything wrong here? 

update.extend('$autoMap', (value, object) => (object ? update(object, value) : update(new Map(), value)));

const someState = new Map();

//someState is a sub tree of state, init as map
const newState = update(someState, {
    ['someMapKey']: {
        $auto: { someObjKey: { $autoMap: { $add: [['key1', 'value1']] } } }
    }
});

console.log(newState.has('someMapKey')); // false
console.log(newState.get('someMapKey')); // undefined
console.log(newState.someMapKey); // {someObjKey: Map(1)}
console.log(newState); 
Map(0) {}
someMapKey: {someObjKey: Map(1)}
size: (...)
__proto__: Map
[[Entries]]: Array(0)
length: 0

**Comment by jinixx** [comment]
Ok, it's not pushed to npm yet.

**Comment by jinixx** [comment]
This new commit is still broken.

```
// this from above replaced the whole object, removing 'amount' prop
update(someState,{
        accounts: 
            {[action.hash]:   
                {$set: {name: 'teste'} }}})

// Error thrown if I change to this
update(someState,{
        accounts: 
            {['102030']:   
                {name: {$set: 'teste'} }}})

// Uncaught TypeError: Cannot read property 'name' of undefined
```

**Comment by kolodny** [comment]
@jinixx It sounds like `someState .accounts` doesn't have a property on the `102030` key. Are you sure `action.hash` is `102030`?

EDIT - Actually it looks like you switched the order of the $set

`{$set: {name: 'teste'} }}})`  
`{name: {$set: 'teste'} }}})`

**Comment by jinixx** [comment]
@kolodny was pointing out that the first update, replaced the whole object which is not necessary what was intended, the second update changes only prop 'name' of action.hash, which wasn't working prior the commit.

This is already resolved in the latest commit by @adelgado.

Thanks!
