### ISSUE TITLE
An example of autovivification from Readme doesn't work

### ISSUE THREAD

**Issue by eljusto** [kolodny/immutability-helper#91]
I've tried an example of autovivification from Readme and got an error:
```
var state = {}
var desiredState = {
  foo: [
    {
      bar: ['x', 'y', 'z']
    },
  ],
};

const state2 = update(state, {
  foo: foo =>
    update(foo || [], {
      0: fooZero =>
        update(fooZero || {}, {
          bar: bar => update(bar || [], { $push: ["x", "y", "z"] })
        })
    })
});
12:49 Uncaught Error: update(): You provided a key path to update() that did not contain one of $push, $unshift, $splice, $set, $merge, $apply. Did you forget to include {$set: ...}?
    at invariant (12:42)
```

**Comment by hoytech** [comment]
FYI update-immutable requires no special syntax for autovivification:

https://www.npmjs.com/package/update-immutable#autovivification

**Comment by andreiglingeanu** [comment]
It actually worked for me, you sure are on the latest version of the lib? Here's a runkit playground where I've tried it: https://runkit.com/andreiglingeanu/autovivification-test

**Comment by kolodny** [comment]
Yep, I'm getting the same behavior as @andreiglingeanu 

@eljusto Can you provide steps to reproduce this issue?

**Comment by SeaOfTea** [comment]
As @andreiglingeanu has suggested, I had this exact issue when my library was pre [v2.6.0](https://github.com/kolodny/immutability-helper/releases/tag/v2.6.0). This is where the new syntax that is shown in the readme was added. So try updating past v2.6.0 and see if this resolves your problem.
