### ISSUE TITLE
[Bug] Typings and $unset

### ISSUE THREAD

**Issue by SaphuA** [kolodny/immutability-helper#92]
`update(data, { $unset: [3] })`

Gives:

```
TS2345: Argument of type '{ $unset: number[]; }' is not assignable to parameter of type 'Query<Data[]>'.
  Type '{ $unset: number[]; }' is not assignable to type '(old: Data[]) => any'.
    Type '{ $unset: number[]; }' provides no match for the signature '(old: Data[]): any'.
```

**Comment by andreiglingeanu** [comment]
That's actually expected, because this:

```javascript
let data = {3: 'value'}

// using a string
data['3'] // => 'value'

data[3] // => 'value'
```

The explanation of that would be that `keyof T` treats they keys as a string, because really they are a string. 

More info: https://github.com/Microsoft/TypeScript/issues/13715

For now I'm going to just allow `number` until we get a better solution.
