### ISSUE TITLE
[Feature] Typings should export the Query type

### ISSUE THREAD

**Issue by SaphuA** [kolodny/immutability-helper#93]
I have a situation where I want to pass `spec` into a method and would rather not use `any`.

```
private updateData(data: Data, spec: Query<Data>): void {
```

But the Query type is not exported so this is not possible without using `any`.

**Comment by andreiglingeanu** [comment]
Use it that way (will be available in `2.6.5` after we merge #94):

```typescript
import  {Query} from 'immutability-helper'
```
