### ISSUE TITLE
$push overrides other data as well

### ISSUE THREAD

**Issue by MarvinDuanePChua** [kolodny/immutability-helper#99]
it works the first time (I pushed "taskName": "aaa" to percy)
`[
  {
    "todoTitle": "percy",
    "task": [
      {
        "key": "0",
        "taskName": "aaa"
      }
    ],
    "key": "0"
  },
  {
    "todoTitle": "marvin",
    "task": [],
    "key": "1"
  }
]`

but if i push to another parent array like carol, percy's taskName gets edited as well

`[
  {
    "todoTitle": "percy",
    "task": [
      {
        "key": "0",
        "taskName": "bbb"
      }
    ],
    "key": "0"
  },
  {
    "todoTitle": "marvin",
    "task": [],
    "key": "1"
  },
  {
    "todoTitle": "carol",
    "task": [
      {
        "key": "0",
        "taskName": "bbb"
      }
    ],
    "key": "2"
  }
]`

and here is my code btw (index is an integer)
    `this.setState({
      todoList: update(tempTodo, {
        [index]: {
          task: {
            $push: [task]
          }
        }
      })
    });`

note that when i push, the items would not exceed from 1. it always just overrides the old value with the new one

**Comment by MarvinDuanePChua** [comment]
somehow this was solved when i did this

let storage = {
taskName: task.taskName,
key: task.key
}

then pass storage instead of task

**Comment by kolodny** [comment]
I'm not sure I understand how to replicate this. Can you provide a the original state and the call to `update`?

**Comment by kolodny** [comment]
Closing for now, feel free to reopen if the problem persists
